---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: cluster-apps-direct-pv
  namespace: flux-system
spec:
  path: ./kubernetes/apps/kube-system/direct-pv/app
  prune: false
  sourceRef:
    kind: GitRepository
    name: home-kubernetes
  healthChecks:
    - apiVersion: helm.toolkit.fluxcd.io/v2beta1
      kind: HelmRelease
      name: kube-system
      namespace: kube-system
  interval: 30m
  retryInterval: 1m
  timeout: 3m
