apiVersion: v1
kind: Secret
metadata:
    name: cloudflare-ddns-secret
    namespace: networking
type: Opaque
stringData:
    CLOUDFLARE_EMAIL: ENC[AES256_GCM,data:Jksmvdmxi355ShHQ102/,iv:LMKLOahbiVDjMDiyOGy0h3mKL7sXJnXk9Asjr4/plyw=,tag:H97YsyYLAVmAp+U7aSN5Tw==,type:str]
    CLOUDFLARE_APIKEY: ENC[AES256_GCM,data:/L5pBMCUTgctRcTLfiwKsYFheRSKijubBxxBM2qmAy0Mwhww1Q==,iv:r+cptPRA/gWlbcSNhgeUGLJyvapSIFzDynX2t2fbSr8=,tag:5NOdqSblKEm6WWQCM4K9ZA==,type:str]
    CLOUDFLARE_RECORD_NAME: ENC[AES256_GCM,data:wyglUN3cqaFOFeHcOEI=,iv:LOR6V2AYUsxchq92fT0n13sJj10WOSqmchq88auk5IE=,tag:CTNsBQ9CBaUz53a6vaMo0w==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1utfeyvqq4ayjnc5ap5ymst4zv008vw3eltpp9cejz3hy4yvnascqxjxn09
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBuNzBGd2xHd3ptSEI4ZTBY
            MDRobDN2S0pnT2lKaW9PN1JsNUFhSDljUlZzCnJVZkRIWmc1K01hazVVQmtyTkEw
            MmM2cVVsYjJkK3NzOHhQNWJWbGpyVEkKLS0tIExRV2JjamVVVjdIekg4RnhTSDFG
            ZWZiUWVuYlNyWVlPNUI1VDloMTZRUVEKEY4jjuydF2rtApqy13yA6ueKnGa9e5LK
            tq10D7W4kWgrNLTfxfThWzIUJRrzJeIJ9ztxc9a4mN8qoXQeSIkDFA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-01-20T20:25:59Z"
    mac: ENC[AES256_GCM,data:d9KgZjGKrLocJoyixiw5y2VNx2HTg9hrCbibmcDupuKJwq1Z3mRiliSK3Mh2kk8F172C6akOqYAva+Ivf/fH+2T6CuWPrzV39ZAXhLM8VyQ0aylQqUYMLH+720Y+4DjB28GSzweutZaql2uLe+VRseAQfBmJcva6m+UPO4b27nY=,iv:boeTQrL2kwlPAHObjId/QkGW3V0+Op2+cM44O6Y42Jc=,tag:9+lqo00j3Zwt1SQpx0VrLg==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
