apiVersion: v1
kind: Secret
metadata:
    name: cloudflare-ddns-secret
    namespace: networking
type: Opaque
stringData:
    CLOUDFLARE_EMAIL: ENC[AES256_GCM,data:Gl/Yn2pMgBQCvLqjq/cM,iv:Iv3386U5B1e3ewC5wr7rh0Pxe1Rh6FRPVz624JB/TlM=,tag:RdajrK/qk/KcerSxT9HTkA==,type:str]
    CLOUDFLARE_APIKEY: ENC[AES256_GCM,data:zf1PVbdCXOflursEOahw3/Fnoqd5DXzV43gVIBxmNdTHdigfjA==,iv:V1hFDnFSaF2vHqMwL4bZNt+o4JwWYBanvHkMQgy0J9I=,tag:ATqhx28rSY5dBwMTj8J39g==,type:str]
    CLOUDFLARE_RECORD_NAME: ENC[AES256_GCM,data:AmUL/JxknZl0z5/RVgY=,iv:/4TqIDK0PbOygOzUXKf0RAmK0q077/XiuAMdNIEeXwc=,tag:2LTNzOpa8b0CbAfO8ue/kg==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1utfeyvqq4ayjnc5ap5ymst4zv008vw3eltpp9cejz3hy4yvnascqxjxn09
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBJZ0lUNXpwZFEwYUhrVmRR
            VTMrRUlWc0pwamZ1T2hFSDJXUWE3R2tWaWxvCmhPaGN4NktKaXFTbXBTU0NoQVB6
            bE5wRlpNcGIyNVQ0YmpoS0c1bWZTc2MKLS0tIExqL1QyNUtKVitYdWxSaU9zdTdQ
            dElIckJkbWp6NE40WTE4T21mUTBVVVEKn8YFdpFKQkTUioPXuRMwOuMJIXH94dhS
            9HWXEojHAXxQKQRDPou7QEx2tF0/92SHt3K9+HesPF7PkvHjlCgdHQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-02-22T02:56:50Z"
    mac: ENC[AES256_GCM,data:vwWVHalz2Pmvvq56nyP8lkxVkomPnBe1eytXRj9DlWfCeUDrXIkeCpIOhICoAl2X3BszZYx5aF4MtcE6tZOxAvp+d7bQvWaIjvpdUGc38ehNdwfFk7fEr/27JuhoLXvToq+HmXl3DN8nJgs1J8fAOEviNPnoe8naDDZ1CiVRtPs=,iv:upRBWl+MtK1CiccIAa4ai9ieFpUNLXdIEfKo+oijRRg=,tag:j2xJbw0JiQ36U02i/G2tdg==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
