---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: zfslocalpv
  namespace: openebs
spec:
  chart:
    spec:
      chart: zfs-localpv
      reconcileStrategy: ChartVersion
      sourceRef:
        kind: HelmRepository
        name: openebs-zfslocalpv
        namespace: flux-system
  interval: 15m0s
  values:
    analytics:
      enabled: false
