---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: cluster-apps-seaweedfs
  namespace: flux-system
spec:
  path: ./kubernetes/apps/kube-system/seaweedfs/app
  prune: false
  sourceRef:
    kind: GitRepository
    name: home-kubernetes
    namespace: flux-system
  healthChecks:
    - apiVersion: helm.toolkit.fluxcd.io/v2beta1
      kind: HelmRelease
      name: seaweedfs
      namespace: kube-system
  interval: 30m
  retryInterval: 1m
  timeout: 5m
