---
apiVersion: source.toolkit.fluxcd.io/v1
kind: GitRepository
metadata:
  name: external-secrets
  namespace: flux-system
spec:
  interval: 1h
  ref:
    branch: main
  url: http://github.com/external-secrets/external-secrets
