---
apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: GitRepository
metadata:
  name: gpu-operator
  namespace: nvidia
spec:
  interval: 30s
  ref:
    branch: master
  url: https://github.com/NVIDIA/gpu-operator
