---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: localpv
  namespace: openebs
spec:
  chart:
    spec:
      chart: openebs-localpv/localpv-provisioner
      reconcileStrategy: ChartVersion
      sourceRef:
        kind: HelmRepository
        name: openebs-localpv
        namespace: flux-system
  interval: 15m0s
  values:
    analytics:
      enabled: false
