kind: ENC[AES256_GCM,data:Qt8Ml3C0,iv:dLeeTAuOcJMawx1PjIkH7J4ImEILXdAEAMW0R3WmxFs=,tag:Q6eiaA88ZuDPABTr8AohyA==,type:str]
ansible_user: ENC[AES256_GCM,data:gnzu9eY=,iv:F2JJ5rEquunjEr/RKEVQWJyjjTD9Cr2p5jVSkdcnjFo=,tag:xrdZk3JSL6yVZNsPMcf2Lw==,type:str]
ansible_become_pass: ENC[AES256_GCM,data:WaLzTi8pggnn8VUk,iv:EbC6+MUpqMHX+zEw3Cm5cyn/59oU6tKpj6eKbsmO8ks=,tag:4Dpxsfwiw44sCe2BepHbEQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1utfeyvqq4ayjnc5ap5ymst4zv008vw3eltpp9cejz3hy4yvnascqxjxn09
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBGMmRhWFFMaFJkdjdjcW1m
            M3RmRVdiUXJzanlTVGxIc0ZTdXZ3RDlvdFhrCjRvVEt6Y0poMTk4cS9Cd3NDMGI2
            U1NDa1RXdWRoVE9PWlhPMmhMRTk2ckUKLS0tIFc3VTFxUXdsYzVrOEVEdUpWL3k2
            KzU0RXpiRU9zRWRiR1BUV2YrSE80UVUKMtYQjkq4ZMdnet9cVYybF4atz+wDCsyB
            NWjUg8XIDrCXKH8OoX9OjwDe2h0WP3ZoFrEjhSpJ7ygkFq9HLqc5Nw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-02-22T02:56:50Z"
    mac: ENC[AES256_GCM,data:XQthMonUETZKUxPGzFdps4KU3oBim+Rld3/b3oZNcrNO8bsxdJs40tQ09M2HnX5/OvUtvr6AOEjFydy+bFC/n1R+2IFbM2o0eIHuLOo6qcaivk1mLeM+Tyysg9anFbCfhZaXnaIE6AjzQlXiJLb866GIoLuEK5jRhT2cWN1CNHo=,iv:t6jrszSSCmhtV8UXMJ9yMAKgYcz4F/f2qKJrB27zuQM=,tag:RIOXl51l7BcaTZNaVbxySQ==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.7.3
