kind: ENC[AES256_GCM,data:2l+cJzQv,iv:LOsd0ZWt+TUfWoKsHbSB3i10AO1eFUXUoLEi6INrI+c=,tag:alnTmsDOXOvJMdZqvhN04w==,type:str]
ansible_user: ENC[AES256_GCM,data:07DuACg=,iv:AB309z5Z1PU/HV6bVxDd5nboiqwLhAKkm0xSVlQBPZA=,tag:MNi2vPkJBzbTLEdtAueuQQ==,type:str]
ansible_become_pass: ENC[AES256_GCM,data:DCDe3xTlDAyle13S,iv:0ReNBbkwsU2yONe+sge8yZu/0tNZHQpK6i/vnadpv6A=,tag:UKshEoBYrIypDFPx3qSbXg==,type:str]
disks:
    - ENC[AES256_GCM,data:tinasQBuDEk=,iv:Hxosb7sFPqqbO38pzAISsjmPUp6GNeSRo8KT+cjtbaY=,tag:JR7f4rrN+SoA60n3nVbQsA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1utfeyvqq4ayjnc5ap5ymst4zv008vw3eltpp9cejz3hy4yvnascqxjxn09
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBXQmxwb05aajZyQnVFRXRm
            b2RYa01PWEVlQjM0MVg5c210aHNmNFlLdkRBCm04d1lwenRrL1I1WjR1V0lKMFE3
            eFhPSUQxUENtQ3NINW5VVmNYZmRLRDQKLS0tICtTZzZCTlk4K0dlbnFWTzdtUDZJ
            MTNmQVZlRlMwMmlreXhkVGRydVBFUGMKMsf4IFyQyPvc7e0EuZUuol0BlCRhVDGT
            qZQgfwb/Q2voksmz7zoKgSyswgwOADWR8sqNPEzbr5UPhGuILLnudQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-03-08T00:30:08Z"
    mac: ENC[AES256_GCM,data:byyecA0mPxQLMYefO/gvoeN0vYqcJu31SzjBXnldgSAdJadCsgD1RcZ3rDpTsbpOrNj6PNQHHH4WWiIVw3/ABK/pER6XKox4lK/f7IszZb7f6c7CXuYLVhZNyc4eOanTES1PVZuzkoGjq4VTj81J5toEOIP8ud9aoD6DeHX6F9Q=,iv:9rkHqaW7/CATaW3DJkamknw3wuHFHZmmZBQmBzapab4=,tag:K8P1kTC1K4gZkV+5GDdmcA==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.7.3
