kind: ENC[AES256_GCM,data:XBM0kXYA,iv:pQ0MTDsEdAQ86qtmw8n3RN+5055XrIZp7kWMZs9zw2Q=,tag:P9UDmJLLb3vk9NEqozs85g==,type:str]
ansible_user: ENC[AES256_GCM,data:qNWkd50=,iv:rbh5pCisbT7Rfy/3ffoo/4Vq9DySIGVjOcB364DOlzw=,tag:h17c9R+LUg0tBFij+dEIzQ==,type:str]
ansible_become_pass: ENC[AES256_GCM,data:7hTFVuIQksUgSGq4PnKP,iv:5WeW+IaOT9uMXyo6kmgWugSGzoxEkqGGMkhrJP5coo0=,tag:8VlhkCSxzAkUcCZRdl25Eg==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1utfeyvqq4ayjnc5ap5ymst4zv008vw3eltpp9cejz3hy4yvnascqxjxn09
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB6Y0dFQWwyM09wYWNzYnYy
            YmlDK2FSSDBzc2x4WlU5dWM2QWEvays3NENrCnJISEpxcFFjN3NkbTRlWkhjTGtR
            RnpPVkwzYUVFd0g1Y3Z6Rk44ZWYyNWsKLS0tIHF0cGoweWZ3RDVsUVhzS2lHMWRw
            WGpOV3VtazljQVAyZ0h2aVBlV0Flc3MK3EFvuCU+LKMjGaHEXUMheHKDXQE2Fc9d
            uRz7djVfLH0r1QTIQoSm9Ta3nkihde8qrGcp/B7nlZAAfnZUTQn4Bg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-01-20T22:17:28Z"
    mac: ENC[AES256_GCM,data:qj9TDihx6bn/S8VpTmq0F0UmWkPS6EfFDDuYHVqSA3T0pUeeWCgsIIuZsCrS2tQULnZlHDRGzEYqmqe51ky315GeF3qqR9JyXjQvAt20V6UrT+xVeKCohn354mJGEHHiJrC/FpEEyhqVTcAv+TirSgJKGQQFQr5XAg59UAtW8uI=,iv:TuLNgts3SVyMYI3n3/0Kuxjwy3PkSVTylsFqfDP4R20=,tag:+6KTTdpAPb3dUuCbwJAV9Q==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.7.3
