kind: ENC[AES256_GCM,data:xpvJLqIz,iv:HT3J6xvBYS6SFOF5sWR5i+papPWwTLdS3qtu62HOeB4=,tag:vJXtXVRN3Xq7cyhUQyx2gQ==,type:str]
ansible_user: ENC[AES256_GCM,data:3IXqYa0=,iv:pCmEkps/Eg4xABpzmXNjzYkKpMrRgIRXF3weu84s+Gc=,tag:s/DuPlhwGXWq9QveBmMdPw==,type:str]
ansible_become_pass: ENC[AES256_GCM,data:aIe1w9G2MicToelN98y1,iv:125D1oILwoZ1N1WZvEjvFnEZ4UmJuwIPIIEItVgoH0I=,tag:gDVFCejL3l33azPK9oKfsg==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1utfeyvqq4ayjnc5ap5ymst4zv008vw3eltpp9cejz3hy4yvnascqxjxn09
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBFeEJtRzdjUEE1YW1aKzVw
            MGx3blkvRnRqNW15SzVjVmlUZ3hNeFF3dVNBCnlYWVloWjFzdDJrWjZvRHlrOFlK
            bERROFZtMzZNOEE5SCtQeGN6VFJOTmcKLS0tIDJPaENHcTQvM1VSZ2crTE5pZTdj
            dDk0RmNaRkJ1Mk9PWHVNRmcrUUg1YlkKyEqtgCpn1jWnB6xXaStbEbusGDU2LQRp
            8pbyJ3fVROCJM6nZKVRwucMwm9nEHLRda+bJ1MK+n5JG49RZOyyQXQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-01-20T22:17:28Z"
    mac: ENC[AES256_GCM,data:2Txn8MVEBfPP8iMEs5soXY/kVkHg68iWk/QdwZHcteNFpaBO1d92U353p3GAidbeNc8ccreYEh5IUxeKomuR+5tXQhJgKUGiynXWAkYgWBYCaWeDDQCrCT0cvQFB8+thKQWYOfpBARrU2JDb4u0zkxSwlH0l7Zjrs6eHUK2jjDU=,iv:N688q06ZXSVo3VzLiu5pMMKltITekcdPmaqK9HDFsFQ=,tag:2wdLbM1RTsWgVxnfQPf4aQ==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.7.3
