kind: ENC[AES256_GCM,data:64VrgCTc,iv:LhwyJuwsN3/YG57VMbKl9K6pKWyhGpHnGsyGYUnH1M4=,tag:gjFwuTsdsRdaFEBV6/gziQ==,type:str]
ansible_user: ENC[AES256_GCM,data:bqFqlqE=,iv:btlS2dM7KfzG4gw3T+AKPqVlV6L5TJxoOiSMJEba+es=,tag:t9w6v+LL8nayTN9b5ZiVTQ==,type:str]
ansible_become_pass: ENC[AES256_GCM,data:99W8bJhXkK0xvsfE3hQZ,iv:alrQIbKQ40e1jK1v1PIbMcOhTUT2zNWp8YMCTb+cPTc=,tag:7T9zP5iqe2UDZ7R/lGUv8A==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1utfeyvqq4ayjnc5ap5ymst4zv008vw3eltpp9cejz3hy4yvnascqxjxn09
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA3dndTZ2tXQnJ6S3JZZ2xl
            cXVXc0htUk9DelZ0QXZpdGM3cTVXVldNVVZvClRscnlhNWFpbjB1L0ExTGlrU3h6
            YS8yYW5JYk1xUzdVbFYvME5XbzZzZk0KLS0tIFU1WFVEbVQ5UWZZcUZhTTVOa2FG
            TDFkSkZsbWFJZWVqWFNxRDR2M1lVN1EKTyjsHJGAsUT972ezwrwV3qG/i8zUAlEO
            k3OJ97PtZkje3XhDOM+wvemzh20JHaC+BUQk0+W2BG70/bTRf3d6LQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-01-20T20:46:38Z"
    mac: ENC[AES256_GCM,data:LDRPkUl14UYoYa/+3c773eDKWDyeG9jZ3job4i/A6mMooAZj4ncNJ1XaXVSs6iTgcG7+BzHx4hpA4dNwLsA2kPk/IciiasbDP4wPpmIfZP9xVfZ+ZlwHwTq5Duqp7J5C2rkovzG/xRhSqiKsEQFrI8NDAYk0LGWQKn0mfSJcysQ=,iv:47Y3BbSXNfMUgJGCIJ82xK9rDr8NNJSQ8kB8IkZ6yus=,tag:Ux/fcBqwnO/fMjs90lCMPQ==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.7.3
