kind: ENC[AES256_GCM,data:fjQ0cNHB,iv:QoXoyQ1moPPOZ2GTPymaxDCDyftXHcVguSFRNACTOuY=,tag:BcPK2BwUa6C8tuXgccFEiQ==,type:str]
ansible_user: ENC[AES256_GCM,data:xEGNsBc=,iv:M3sniDwN0gVHlutrZMkntraa+eK33ECDkeCyE5EIx0k=,tag:6Riov8Bcj3lB8oHKjURb4w==,type:str]
ansible_become_pass: ENC[AES256_GCM,data:IXFOi4xNFrkJBGuAP9bN,iv:+/XQIrNly1f2WF8Z89MouI6tx8apGyXDa+QCPbVw48A=,tag:S0OKRr/4i4+fODWuOa0/EQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1utfeyvqq4ayjnc5ap5ymst4zv008vw3eltpp9cejz3hy4yvnascqxjxn09
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBqVUNDMU1qN0QvbjlZUVd4
            K2dEMWFLOUJVam5kN1Q2UUQwTGphY2kwK0RrCm9uLzhUc1hMM01vaG80cWREMExK
            bitpNlNHc0plNGxZbWFUY0lMUzdqUFkKLS0tIEltNWhwaFAxSmtUQkNESWRrc0o2
            UXhPZXU3b2RaOGZRZ2J5cGh5NldWbUkKDehcMK+M9aWUW6QsOyxV0U0loJ9Ub9D9
            3ATOddTJ4UwwzheAUGY679OOX1a3i0KPaqvb7XNtLmJcQ9j+ti6XfA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-01-20T22:17:28Z"
    mac: ENC[AES256_GCM,data:lDOPFFj6K6z7dLxUjjyKoWw04diYxRKbfyNiOsteC/ocgmDwAmqrYuN+q4agmU7uDOE7a6gJexyzTQpCcqsJOK9G25nPw9Yps/cvhtT20fiMXcpkRl+ynEyrquU23amOOqHgs7YLeur/bkqdB8v1OVfc80km8oewkwCCF9V8fxg=,iv:DVZyhMijA8wk7cElCQc04yDGFM5gWcbBVfnfB0IIvwE=,tag:8maRkDVPeFDO8FBNnPv/dQ==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.7.3
