kind: ENC[AES256_GCM,data:S7UfvQDc,iv:rtDDOBmjawzN+BgekTsuPGOETeWRzEro7U6tx3p20hI=,tag:uAM1Rzk+MgAZxQv6Bp7ZKg==,type:str]
ansible_user: ENC[AES256_GCM,data:6X9g4h8=,iv:Htt6qyEl+EmxX1lIYpMfpD6SpGB+Pse5zb2NY2LLrJ4=,tag:X4YgXEAztGKjZkTbwkMTsA==,type:str]
ansible_become_pass: ENC[AES256_GCM,data:4/N8MggS0XYsWiB/gwY1,iv:HQrCwkETzENQjIQgYk4cMmkdlK0rStFRPRpCHOnVy8w=,tag:eHixRoi9SknAXPhru2zdmg==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1utfeyvqq4ayjnc5ap5ymst4zv008vw3eltpp9cejz3hy4yvnascqxjxn09
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBVY0xROERwOXNGQ01WMCto
            bWFhNkdZVEZkWVZJbXNiKzRVNFVBaS9UMGk0Ckp1OFlEcDFYM0F4UzhjSkF6RkJE
            WEpISHdxeC9ER2hMN3BuYytSdmU1dVUKLS0tIEZsVFZIVVJZb2JWOVNxbHh1MGQ3
            aUVNbnRIbzdScUo2alU2dmgrVnl6U1EKjFitRIsIbrngb2uImZPCWXIRkJSeLSc4
            ZlVCJbBZllkoQySny7mgV78dxI9mipPQakdtVxfCmgkDkX6+vUXZUw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-01-20T20:25:59Z"
    mac: ENC[AES256_GCM,data:UU0jV/uGox/j1RIPQYAC8saPgxQum2EmdICA1ogRJ87XIRzB8UcsVx6pM9rYogqwU9zKIER2Jvoass2GUt78h/21M6PFBuRhPLfF9GZgFg2H7L0GQBZA/c0yczyT1RcSNrgEQJYrD+D0FKTm++ILVEUeXFPKDVwC2i8UDeXOPFE=,iv:oB5yuh7hWKprK2MniBwLKfsrGw2uz90pAkMNfbpYH3E=,tag:hABx0uPzaaM/8KzTT5THUA==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.7.3
