kind: ENC[AES256_GCM,data:cTKh48KG,iv:JiYlLqMKEwNYzVWhNlgBZdIuOpieEVtUhr/KV6XIrGM=,tag:ngx1o0titVKuTprZr1zgHA==,type:str]
ansible_user: ENC[AES256_GCM,data:pNI0eL8=,iv:stq6ppEoA+bTKLv+JeTpNqY5Bl7ESRMszALHrpXOBgY=,tag:HRzsDoN4Ref+ijCj7R0S8w==,type:str]
ansible_become_pass: ENC[AES256_GCM,data:BnRuj9uigzUQuRriC3ku,iv:j+N3tgEFq211eTZriNp8qIOa72GYldxteHEm0eX0HqQ=,tag:LAdjbtNGcb1ZRE6tGbV6Hg==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1utfeyvqq4ayjnc5ap5ymst4zv008vw3eltpp9cejz3hy4yvnascqxjxn09
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBkaUlGd0R3WU55Mzk3M0tD
            cHhGVWo5NEM2QU45SURMWEdJTmM3NjJrZmtNClQ0OWllSEwzUnE2ekNBQzlseE1Q
            aFlib3h3a1ZpNDMyeHRRUXVraEdXNmMKLS0tICtvdXRHbjZSUWRHbzh5UUhFa3hH
            UTZ6RDR5bEtMMXJWYld4NXM5WFZtK1kKFM3lDVdW1S5CvLMq5BXADN8kw4tlad9f
            VTRuw/Njsbyyz2YTweQ+1FtcRwhd9rUEwv9dtBDMUrNtQoK6hGj/Yg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-01-20T17:41:02Z"
    mac: ENC[AES256_GCM,data:gQ4TDkT1zdd86TYH1uIWZtOWj/gketbSkyWM/QZC1q0rT+cDsnXk88cQQH6PEWyF7qV+cSx4bVX2q+1A5CCgBUjmEMGUNJeEmPDtsiUyIr6ylc0k4NswCDEA3SRlw5Sd0CdOEviumum7/KzOX3J+74sRW8OdGfxNfYAcfn6umKU=,iv:7H+XiNr1vVPa5ZEpPSkzjXZCCJPs3DhIWfdT12VuRhg=,tag:6JuAhWA6I+teWyUotJICZQ==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.7.3
