kind: ENC[AES256_GCM,data:JlbubB9Q,iv:DgK4GgTUn3/5GRmjg81BaXycRJyVJ18P3AlT5lU+tYM=,tag:65vdmWEAh6r5Khsspi/uqQ==,type:str]
ansible_user: ENC[AES256_GCM,data:RrfmV8g=,iv:SCb/owBw3F1nBkTaLM/D+7Dc4QfSvuBMi5I9GWwZexU=,tag:0xE9Zu3M8HTbvyb6vN0m/g==,type:str]
ansible_become_pass: ENC[AES256_GCM,data:PN5CJAtU1Gzb4adKNifb,iv:9CtCGtSueQdq7LAib8D9AhaYFXuAedkTADZ4uKYmRDE=,tag:5bOIQkrZGMj46c/fVnglkg==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1utfeyvqq4ayjnc5ap5ymst4zv008vw3eltpp9cejz3hy4yvnascqxjxn09
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA4USsxa1VReTlrcFYyODgw
            bC9sTkVydThGOTNFNGZidjdYNTVBNGZGdGlRClFGZ3VpS2dia2hVcVRKL3RsRXFE
            WnpiMDNYVkljQzhUc2FoR21vWW9Wc00KLS0tIHJ1OWpOditzaTJ6RjNpUUFwbG9R
            TTg0VCswWlhuRTYyRXlFVlY0THIzOEEKR4s80EIAnvx0pw/Z3yS7BcbwSXhLoc4d
            HuQDZcfmvpnbakN5XeFirJWpJ63hV77munYKeLiqO8ISieACMkdFVA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-01-20T20:25:59Z"
    mac: ENC[AES256_GCM,data:g5XpB64+4wGPRxC2pLBrVnAii5bbKLrzqm7bMb86srEQT3Qp8hnluHTNVzzDVeXkIco0goUzzTmfK12yu5hBgr2kGPXOVMLYZkjJnMhmvqpVfhp9PkemfXaqz1Cdl7smcG+/JX9H9AasV+68BOJIx6lQavrBSweHgatDTSkczu8=,iv:/+4Y+9GRYVMvoYTeM6yajLCoa+bmv9Tt+Mogpb825KI=,tag:71MnCGznAenJKwEjZJF6NA==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.7.3
