kind: ENC[AES256_GCM,data:iDUjMTaT,iv:3PFEIdz5YSD1ByLe94PjnM8gJrXR4yH84jWuKBnTmcM=,tag:IcCZVrPPlRXKWZz8N0MLPA==,type:str]
ansible_user: ENC[AES256_GCM,data:dXeP8cM=,iv:ekX+tqaO0KvdtPG7YdOmWvLqPc57yju9jyrkmypiZPI=,tag:jyTn5nB0m07Xu8ORLqVrtg==,type:str]
ansible_become_pass: ENC[AES256_GCM,data:lIICqnxyAjnVyyR3AgFo,iv:2VJ5V+6iIYoT8D/iACBGbUQRKPywJkTwgaIQfFvQfXA=,tag:FNTvJy/aAArYDMVYGyzG7g==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1utfeyvqq4ayjnc5ap5ymst4zv008vw3eltpp9cejz3hy4yvnascqxjxn09
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSArV1VjWDVPdER6K0pFK0Ez
            V2NEdEZaTVEzeW85V1JydEJKZjBnS3FwUG1rCkJRWmpJcVZnck1ERTd5NThQSklq
            MlA3ZFF0ajRYNVhHWHk5SWIvK2V0elUKLS0tIEdsSzlSQUFvS2hINkx2N3p0VG05
            Nkk1UkNvOHRHNFU5cFh2cnBGUmsyUFEKLtF5O3o4r7cYoPDWHYGQrjWnrhTV8quD
            6FI4DU54xbPNjDALrwWxUVuBchKKWrtJY0VdosS1jKVYvMIGrnHIvA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-01-18T01:44:42Z"
    mac: ENC[AES256_GCM,data:fIxefGgyAnZhFVFMlI3zaJh0m+tvMTcNKpS6QqG22CBQgtYKrVQ4h5iFR2xs8pcTJwneJeb4kQuaSTIK/UXBTceGLHP9iHmComEqITDE5MlWOR+kuzVscUBZ3W6W4+s23YOR9guH3r9fk8Dppb1KBKCQpufWkcW03w7kSNywwFk=,iv:XncB3uxR7+sCE6/+qHkxoLajwj7WRH9X0/f5MfmgxJM=,tag:T01r28ph0QzPzgx3+nBoAg==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.7.3
