---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: cluster-apps-rook-ceph
  namespace: flux-system
spec:
  dependsOn:
    - name: cluster-apps-openebs-lvmlocalpv
  path: ./kubernetes/apps/rook-ceph/app
  prune: true
  sourceRef:
    kind: GitRepository
    name: home-kubernetes
  healthChecks:
    - apiVersion: helm.toolkit.fluxcd.io/v2beta1
      kind: HelmRelease
      name: rook-ceph-operator
      namespace: rook-ceph
  interval: 10m
  retryInterval: 1m
  timeout: 5m
---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: cluster-apps-rook-ceph-cluster
  namespace: flux-system
spec:
  dependsOn:
    - name: cluster-apps-openebs-lvmlocalpv
    - name: cluster-apps-rook-ceph
  path: ./kubernetes/apps/rook-ceph/cluster
  prune: true
  sourceRef:
    kind: GitRepository
    name: home-kubernetes
  healthChecks:
    - apiVersion: helm.toolkit.fluxcd.io/v2beta1
      kind: HelmRelease
      name: rook-ceph-cluster
      namespace: rook-ceph
  interval: 10m
  retryInterval: 1m
  timeout: 20m
# ---
# apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
# kind: Kustomization
# metadata:
#   name: cluster-apps-rook-ceph-addons
#   namespace: flux-system
# spec:
#   dependsOn:
#     - name: cluster-apps-rook-ceph
#     - name: cluster-apps-rook-ceph-cluster
#   path: ./kubernetes/apps/rook-ceph/addons
#   prune: true
#   sourceRef:
#     kind: GitRepository
#     name: home-kubernetes
#   interval: 10m
#   retryInterval: 1m
#   timeout: 50m
