---
apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: HelmRepository
metadata:
  name: openebs-lvmlocalpv
  namespace: flux-system
spec:
  interval: 30m0s
  url: https://openebs.github.io/lvm-localpv/
