---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: cluster-apps-minio-tenant
  namespace: flux-system
spec:
  dependsOn:
    - name: cluster-apps-minio-operator
    - name: cluster-apps-openebs-lvmlocalpv
  path: ./kubernetes/apps/minio-tenant/tenant
  prune: false
  sourceRef:
    kind: GitRepository
    name: home-kubernetes
  healthChecks:
    - apiVersion: helm.toolkit.fluxcd.io/v2beta1
      kind: HelmRelease
      name: minio-tenant
      namespace: minio-tenant
  interval: 30m
  retryInterval: 1m
  timeout: 3m
