---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: minio-tenant
  namespace: flux-system
spec:
  dependsOn:
    - name: cluster-apps-minio
  interval: 1m0s
  path: ./kubernetes/apps/minio-tenant/tenant
  prune: false
  sourceRef:
    kind: GitRepository
    name: home-kubernetes
