---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: nextcloud-pv
  namespace: default
spec:
  capacity:
    storage: 500Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: ceph-block
  claimRef:
    name: nextcloud-pvc
    namespace: default
  csi:
    driver: rbd.csi.k8s.io
    readOnly: false
    volumeHandle: nextcloud-pv

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: nextcloud-pvc
  namespace: default
spec:
  volumeName: nextcloud-pv
  resources:
    requests:
      storage: 500Gi
