---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: nextcloud
  namespace: default
spec:
  accessModes:
    - ReadWriteMany
  #persistentVolumeReclaimPolicy: Retain
  volumeName: nextcloud
  storageClassName: ceph-block
  resources:
    requests:
      storage: 500G
