---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: nextcloud
  namespace: default
spec:
  capacity:
    storage: 500Gi
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  storageClassName: ceph-block

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: nextcloud
  namespace: default
spec:
  accessModes:
    - ReadWriteMany
  #persistentVolumeReclaimPolicy: Retain
  volumeName: nextcloud
  storageClassName: ceph-block
  resources:
    requests:
      storage: 500Gi
