# yamllint disable
kind: Secret
apiVersion: v1
type: Opaque
metadata:
    name: nextcloud
    namespace: default
stringData:
    ADMIN_USERNAME: ENC[AES256_GCM,data:LVA5dp8=,iv:4F7FKcZucf9GsVcws1352B8onnlFj6kL9jb3ngcxS28=,tag:ZUGeF47xp3mcSqwYYvwH5A==,type:str]
    ADMIN_PASSWORD: ENC[AES256_GCM,data:xljTohMVBoxFvnf2,iv:PZJG0SIrcLMm2GqqS8FpfTNOI3n6cAKnm9m051JAD+M=,tag:95UjYptxILBYYy4jfg4GjQ==,type:str]
    REDIS_PASSWORD: ENC[AES256_GCM,data:+GC5W5O6qCYLrcU2,iv:HbxM9KrT6q5bGMxRhH62DpesqyIN59vH98STayKXkt8=,tag:oNeAwuagR3sgt9jLfaTmDw==,type:str]
    POSTGRES_PASSWORD: ENC[AES256_GCM,data:vsZgXyhXj/Sc497q,iv:FkiSzDSiMWwuHW2vyMvLCbxA1dk/RRsSTWu65rvku8Y=,tag:Fe4M45o8OlhTsQjbwQtyaw==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1utfeyvqq4ayjnc5ap5ymst4zv008vw3eltpp9cejz3hy4yvnascqxjxn09
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBpaitjWkgrbHprMk0wQlZh
            ZXYvU1JaV2t3U2xoVDYvaXVlWjNCWjVudFVZCklrcEx0RXlRb0wwRkE2RjZGQmhw
            SkxzZ1RpSkpuRjBoV0pnLy9XS2h1ZUkKLS0tIHl1MVhhdk43aEtYTnpHZGJ3RWJB
            b2tsek5aNWRMRmZDSC9NOHNnWXdVYVUK8oTbwyLhohm9dLoZaNHSozg2d3B0jwI4
            00M1ZWo1zlszpbyA7eGPzo6g6oAcsIv8IlInaOKVIHeWa/fWwenE1Q==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-03-01T06:52:04Z"
    mac: ENC[AES256_GCM,data:y/kpPRooaUnsDxhSvQzibO2vL05Ze1O2B86rEdK4UTYewy0+x+hAIY3T5wFZ/GsLoYXumK+U+6tSUzDlAzCvzVjM8RP+yhWItDwb0+Tn8Y4IaNeB2CEqi8ds820klgDw3wmAjgoQQGMxeKXUyZEYrI8++b78w2PegVUlpmE4VEk=,iv:ssiv9BnFdZZ/HoB+cZOFLrAdlmzfXrtePsdHMVQWGsM=,tag:+XCjHYxmIzdmlkiEH66aog==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
