---
clusterName: nanocluster

talosVersion: v1.3.3
kubernetesVersion: 1.26.1
endpoint: "https://10.13.10.98:6443"

additionalApiServerCertSans:
  - 10.13.10.98
  - nanocluster.rengo.dev

additionalMachineCertSans:
  - 10.13.10.98
  - nanocluster.rengo.dev

cniConfig:
  name: custom
  urls:
    - "https://raw.githubusercontent.com/bjw-s/home-ops/main/infrastructure/talos/cluster-0/cni/install.yaml"

nodes:
  - hostname: nano-0
    ipAddress: 10.13.10.190
    controlPlane: true
    installDisk: /dev/mmcblk1
    disableSearchDomain: true
    kernelModules:
      - name: br_netfilter
        parameters:
          - nf_conntrack_max=131072
    nameservers:
      - 10.13.10.2
    networkInterfaces:
      - interface: eth0
        dhcp: true
        vip:
          ip: 10.13.10.98
  - hostname: nano-1
    ipAddress: 10.13.10.191
    controlPlane: true
    installDisk: /dev/mmcblk1
    disableSearchDomain: true
    kernelModules:
      - name: br_netfilter
        parameters:
          - nf_conntrack_max=131072
    nameservers:
      - 10.13.10.2
    networkInterfaces:
      - interface: eth0
        dhcp: true
        vip:
          ip: 10.13.10.98
  - hostname: nano-2
    ipAddress: 10.13.10.192
    controlPlane: true
    installDisk: /dev/mmcblk1
    disableSearchDomain: true
    kernelModules:
      - name: br_netfilter
        parameters:
          - nf_conntrack_max=131072
    nameservers:
      - 10.13.10.2
    networkInterfaces:
      - interface: eth0
        dhcp: true
        vip:
          ip: 10.13.10.98
  - hostname: nano-3
    ipAddress: 10.13.10.193
    controlPlane: false
    installDisk: /dev/mmcblk1
    disableSearchDomain: true
    kernelModules:
      - name: br_netfilter
        parameters:
          - nf_conntrack_max=131072
    nameservers:
      - 10.13.10.2
    networkInterfaces:
      - interface: eth0
        dhcp: true

controlPlane:
  patches:
    - |-
      cluster:
        allowSchedulingOnMasters: true

    - |-
      - op: add
        path: /machine/kubelet/extraArgs
        value:
          feature-gates: GracefulNodeShutdown=true,MixedProtocolLBService=true
          rotate-server-certificates: "true"
worker:
  patches:
    - |-
      - op: add
        path: /machine/kubelet/extraArgs
        value:
          feature-gates: GracefulNodeShutdown=false,MixedProtocolLBService=false
          rotate-server-certificates: "true"
