---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: cluster-apps-vault
  namespace: flux-system
spec:
  interval: 15m0s
  path: ./kubernetes/apps/hosted/vault/app
  prune: true
  sourceRef:
    kind: GitRepository
    name: home-kubernetes
    namespace: flux-system
