---
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: hdd-lvm
allowVolumeExpansion: true
provisioner: local.csi.openebs.io
parameters:
  storage: "lvm" # unsure if this is required
  vgpattern: "*.hdd"
  thinProvision: "yes"
