---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: openebs-lvmlocalpv
  namespace: openebs
spec:
  chart:
    spec:
      chart: lvm-localpv
      reconcileStrategy: ChartVersion
      sourceRef:
        kind: HelmRepository
        name: openebs-lvmlocalpv
        namespace: flux-system
  interval: 15m0s
  install:
    createNamespace: true
  values:
    analytics:
      enabled: false
