---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: lvmlocalpv
  namespace: openebs
spec:
  chart:
    spec:
      chart: openebs-lvmlocalpv/lvm-localpv
      reconcileStrategy: ChartVersion
      sourceRef:
        kind: HelmRepository
        name: openebs-lvmlocalpv
        namespace: flux-system
  interval: 15m0s
values:
  analytics:
    enabled: false
