---
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: nvme-lvm
allowVolumeExpansion: true
provisioner: local.csi.openebs.io
parameters:
  storage: "lvm" # unsure if this is required
  vgpattern: "*.nvme"
  thinProvision: "yes"
allowedTopologies:
  - matchLabelExpressions:
      - key: kubernetes.io/hostname
        values:
          - droplet-3
          - droplet-4
          - droplet-5
