---
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: nvme-lvm-droplet-5
allowVolumeExpansion: true
provisioner: local.csi.openebs.io
parameters:
  storage: "lvm" # unsure if this is required
  vgpattern: "lvmvg.nvme"
  thinProvision: "yes"
volumeBindingMode: Immediate
allowedTopologies:
  - matchLabelExpressions:
      - key: openebs.io/nodename
        values:
          - droplet-5
