---
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: ssd-lvm-5
  annotations:
    storageclass.kubernetes.io/is-default-class: "true"
allowVolumeExpansion: true
provisioner: local.csi.openebs.io
parameters:
  storage: "lvm" # unsure if this is required
  vgpattern: "lvmvg.ssd"
  thinProvision: "yes"
volumeBindingMode: Immediate
allowedTopologies:
  - matchLabelExpressions:
      - key: openebs.io/nodename
        values:
          - droplet-5
