apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ include "direct-pv.fullname" . }}-csi-min-io
  labels:
    application-name: direct.csi.min.io
    application-type: CSIDriver
    direct.csi.min.io/created-by: kubectl-direct-csi
    direct.csi.min.io/version: v1beta5
  {{- include "direct-pv.labels" . | nindent 4 }}
  annotations:
    pod-security.kubernetes.io/enforce: privileged
    rbac.authorization.kubernetes.io/autoupdate: "true"
rules:
- apiGroups:
  - ""
  resources:
  - persistentvolumes
  verbs:
  - get
  - list
  - watch
  - create
  - delete
- apiGroups:
  - policy
  resources:
  - podsecuritypolicies
  verbs:
  - use
- apiGroups:
  - ""
  resources:
  - persistentvolumeclaims
  verbs:
  - get
  - list
  - watch
  - update
- apiGroups:
  - storage.k8s.io
  resources:
  - storageclasses
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - ""
  resources:
  - events
  verbs:
  - create
  - list
  - watch
  - update
  - patch
- apiGroups:
  - snapshot.storage.k8s.io
  resources:
  - volumesnapshots
  verbs:
  - get
  - list
- apiGroups:
  - snapshot.storage.k8s.io
  resources:
  - volumesnapshotcontents
  verbs:
  - get
  - list
- apiGroups:
  - storage.k8s.io
  resources:
  - csinodes
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - ""
  resources:
  - nodes
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - storage.k8s.io
  resources:
  - volumeattachments
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - ""
  resources:
  - endpoints
  verbs:
  - get
  - list
  - watch
  - create
  - update
  - delete
- apiGroups:
  - coordination.k8s.io
  resources:
  - leases
  verbs:
  - get
  - list
  - watch
  - create
  - update
  - delete
- apiGroups:
  - apiextensions.k8s.io
  - direct.csi.min.io
  resources:
  - customresourcedefinitions
  - customresourcedefinition
  verbs:
  - get
  - list
  - watch
  - create
  - update
  - delete
  - patch
- apiGroups:
  - direct.csi.min.io
  resources:
  - directcsidrives
  - directcsivolumes
  verbs:
  - get
  - list
  - watch
  - create
  - update
  - delete
- apiGroups:
  - ""
  resources:
  - pods
  - pod
  verbs:
  - get
  - list
  - watch
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ include "direct-pv.fullname" . }}-csi-min-io
  labels:
    application-name: direct.csi.min.io
    application-type: CSIDriver
    direct.csi.min.io/created-by: kubectl-direct-csi
    direct.csi.min.io/version: v1beta5
  {{- include "direct-pv.labels" . | nindent 4 }}
  annotations:
    pod-security.kubernetes.io/enforce: privileged
    rbac.authorization.kubernetes.io/autoupdate: "true"
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: '{{ include "direct-pv.fullname" . }}-csi-min-io'
subjects:
- kind: ServiceAccount
  name: '{{ include "direct-pv.fullname" . }}-csi-min-io'
  namespace: '{{ .Release.Namespace }}'