---
kubernetes:
  children:
    master:
      hosts:
        k8s-m-0:
          ansible_host: 10.13.10.61
        k8s-m-3:
          ansible_host: 10.13.10.64
        k8s-m-5:
          ansible_host: 10.13.10.66
    worker:
      hosts:
        k8s-w-1:
          ansible_host: 10.13.10.62
        k8s-w-2:
          ansible_host: 10.13.10.63
        k8s-w-4:
          ansible_host: 10.13.10.65
        k8s-w-6:
          ansible_host: 10.13.10.67
        k8s-w-7:
          ansible_host: 10.13.10.68
