---
kubernetes:
  children:
    master:
      hosts:
        droplet-0:
          ansible_host: 10.13.20.30
        droplet-1:
          ansible_host: 10.13.20.31
        droplet-2:
          ansible_host: 10.13.20.32
    worker:
      hosts:
        droplet-3:
          ansible_host: 10.13.20.33
        droplet-4:
          ansible_host: 10.13.20.34
        droplet-5:
          ansible_host: 10.13.20.35
        droplet-6:
          ansible_host: 10.13.20.36
        droplet-7:
          ansible_host: 10.13.20.37
