---
kubernetes:
  children:
    master:
      hosts:
        k8s-0:
          ansible_host: 10.13.10.61
    worker:
      hosts:
        k8s-1:
          ansible_host: 10.13.10.62
        k8s-2:
          ansible_host: 10.13.10.63
        k8s-3:
          ansible_host: 10.13.10.64
        k8s-4:
          ansible_host: 10.13.10.65
