---
kubernetes:
  children:
    master:
      hosts:
        droplet-0:
          ansible_host: 10.13.20.30
        droplet-1:
          ansible_host: 10.13.20.31
        droplet-2:
          ansible_host: 10.13.20.32
    worker:
      children:
        nvme:
          hosts:
            droplet-3:
              ansible_host: 10.13.20.33
            droplet-4:
              ansible_host: 10.13.20.34
            droplet-5:
              ansible_host: 10.13.20.35
        gpu:
          hosts:
            droplet-oneiros:
              ansible_host: 10.13.20.38
      hosts:
        droplet-6:
          ansible_host: 10.13.20.36
        droplet-7:
          ansible_host: 10.13.20.37
