---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: rook-ceph-cluster
  namespace: rook-ceph
spec:
  interval: 15m
  chart:
    spec:
      chart: rook-ceph-cluster
      version: v1.11.0
      sourceRef:
        kind: HelmRepository
        name: rook-ceph
        namespace: flux-system
  maxHistory: 3
  install:
    createNamespace: true
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
  uninstall:
    keepHistory: false
  values:
    monitoring:
      enabled: true
      createPrometheusRules: true
    ingress:
      dashboard:
        ingressClassName: nginx
        annotations:
        # If the dashboard has ssl: true the following will make sure the NGINX Ingress controller can expose the dashboard correctly
        # nginx.ingress.kubernetes.io/backend-protocol: "HTTPS"
        # nginx.ingress.kubernetes.io/server-snippet: |
        #   proxy_ssl_verify off;
          nginx.ingress.kubernetes.io/whitelist-source-range: |
            10.0.0.0/8,172.16.0.0/12,192.168.0.0/16
          external-dns.alpha.kubernetes.io/target: "ipv4.rengo.dev"
          external-dns.home.arpa/enabled: "true"
          cert-manager.io/cluster-issuer: letsencrypt-staging
          hajimari.io/enable: "true"
          hajimari.io/appName: "Rook"
          hajimari.io/icon: mdi:chess-rook
        hosts:
          - host: &host rook.rengo.dev
            path: /
            # path: "/ceph-dashboard(/|$)(.*)"
        tls:
          - hosts:
              - *host
            secretName: rook-ceph-dashboard-tls
    toolbox:
      enabled: true
    configOverride: |
      [global]
      bdev_enable_discard = auto
      bdev_async_discard = auto
    cephClusterSpec:
      dataDirHostPath: /var/lib/rook
      network:
        # provider: host
      crashCollector:
        disable: true
      logCollector:
        enabled: false
      cleanupPolicy:
        # confirmation: "yes-really-destroy-data"
        sanitizeDisks:
          method: quick
          dataSource: zero
        allowUninstallWithVolumes: true
      dashboard:
        enabled: true
        urlPrefix: /
        ssl: false
      placement:
        mgr:
          modules:
            - name: rook
              enabled: true
        #   tolerations:
        #     - effect: NoSchedule
        #       key: node-role.kubernetes.io/control-plane
        # mon:
        #   tolerations:
        #     - effect: NoSchedule
        #       key: node-role.kubernetes.io/control-plane
      # removeOSDsIfOutAndSafeToRemove: true
      priorityClassNames:
        mon: system-node-critical
        osd: system-node-critical
        mgr: system-cluster-critical
      # cluster level storage configuration
      storage:
        useAllNodes: false
        useAllDevices: false
        encryptedDevice: "false" # the default value for this option is "false"
        nodes:
          - name: droplet-2
            devices:
              - name: /dev/sdb # /dev/disk/by-id/ata-TEAM_T253X2002T_AA000000000000000204
          - name: droplet-3
            devices:
              - name: /dev/nvme0n1
                config:
                  osdsPerDevice: "2"
          - name: droplet-4
            devices:
              - name: /dev/sdb # /dev/disk/by-id/ata-Patriot_P210_2048GB_PBEADBB2211180808
              - name: /dev/nvme0n1
                config:
                  osdsPerDevice: "2"
          - name: droplet-5
            devices:
              - name: /dev/sdb # /dev/disk/by-id/ata-Patriot_P210_2048GB_PBEADBB2211180869
              - name: /dev/nvme0n1
                config:
                  osdsPerDevice: "2"
          - name: droplet-6
            devices:
              - name: /dev/sdb # /dev/disk/by-id/ata-Patriot_P210_2048GB_PBEADBB2211180711
          - name: droplet-7
            devices:
              - name: /dev/sdb # /dev/disk/by-id/ata-WDC_WD120EDAZ-11F3RA0_5PJD7E9F

    cephBlockPoolsVolumeSnapshotClass:
      enabled: false
    cephBlockPools:
    cephFileSystems:
      - name: ceph-ssd
        spec:
          metadataPool:
            replicated:
              size: 3
          dataPools:
            - failureDomain: host
              replicated:
                size: 3
              name: data0
              deviceClass: ssd
          metadataServer:
            activeCount: 1
            activeStandby: true
            resources:
              requests:
                cpu: 1000m
                memory: 4Gi
              limits:
                cpu: 2000m
                memory: 4Gi
            priorityClassName: system-cluster-critical
        storageClass:
          enabled: true
          isDefault: true
          name: ceph-ssd
          pool: data0
          reclaimPolicy: Delete
          allowVolumeExpansion: true
          parameters:
            csi.storage.k8s.io/provisioner-secret-name: rook-csi-cephfs-provisioner
            csi.storage.k8s.io/provisioner-secret-namespace: rook-ceph
            csi.storage.k8s.io/controller-expand-secret-name: rook-csi-cephfs-provisioner
            csi.storage.k8s.io/controller-expand-secret-namespace: rook-ceph
            csi.storage.k8s.io/node-stage-secret-name: rook-csi-cephfs-node
            csi.storage.k8s.io/node-stage-secret-namespace: rook-ceph
            csi.storage.k8s.io/fstype: ext4
      - name: ceph-nvme
        spec:
          metadataPool:
            replicated:
              size: 3
          dataPools:
            - failureDomain: host
              replicated:
                size: 3
              name: data1
              deviceClass: nvme
          metadataServer:
            activeCount: 1
            activeStandby: true
            resources:
              requests:
                cpu: 1000m
                memory: 4Gi
              limits:
                cpu: 2000m
                memory: 4Gi
            priorityClassName: system-cluster-critical
        storageClass:
          enabled: true
          isDefault: false
          name: ceph-nvme
          pool: data1
          reclaimPolicy: Delete
          allowVolumeExpansion: true
          parameters:
            csi.storage.k8s.io/provisioner-secret-name: rook-csi-cephfs-provisioner
            csi.storage.k8s.io/provisioner-secret-namespace: rook-ceph
            csi.storage.k8s.io/controller-expand-secret-name: rook-csi-cephfs-provisioner
            csi.storage.k8s.io/controller-expand-secret-namespace: rook-ceph
            csi.storage.k8s.io/node-stage-secret-name: rook-csi-cephfs-node
            csi.storage.k8s.io/node-stage-secret-namespace: rook-ceph
            csi.storage.k8s.io/fstype: ext4
    cephObjectStores:
      - name: ceph-objectstore
        spec:
          metadataPool:
            enableRBDStats: true
            failureDomain: host
            replicated:
              size: 3
            deviceClass: ssd
          dataPool:
            failureDomain: host
            replicated:
              size: 3
              hybridStorage:
                primaryDeviceClass: ssd
                secondaryDeviceClass: hdd
          preservePoolsOnDelete: true
          gateway:
            type: s3
            port: 80
            hostNetwork: false
            instances: 1
          healthCheck:
            bucket:
              interval: 60s
        storageClass:
          enabled: true
          name: ceph-bucket
          reclaimPolicy: delete
          parameters:
            region: us-east-1
