---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: rook-ceph-cluster
  namespace: rook-ceph
spec:
  interval: 15m
  chart:
    spec:
      chart: rook-ceph-cluster
      version: v1.10.11
      sourceRef:
        kind: HelmRepository
        name: rook-ceph
        namespace: flux-system
  maxHistory: 3
  install:
    createNamespace: true
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
  uninstall:
    keepHistory: false
  values:
    monitoring:
      enabled: true
      createPrometheusRules: true
    ingress:
      dashboard:
        enabled: true
        ingressClassName: nginx
        annotations:
          nginx.ingress.kubernetes.io/whitelist-source-range: |
            10.0.0.0/8,172.16.0.0/12,192.168.0.0/16
          external-dns.alpha.kubernetes.io/target: "ipv4.rengo.dev"
          external-dns.home.arpa/enabled: "false"
          cert-manager.io/cluster-issuer: letsencrypt-production
          hajimari.io/appName: "Rook"
          hajimari.io/icon: mdi:chess-rook
        hosts:
          - host: &host "rook.rengo.dev"
            paths:
              - path: /
        tls:
          - hosts:
              - *host
    toolbox:
      enabled: true
    configOverride: |
      [global]
      bdev_enable_discard = auto
      bdev_async_discard = auto
    cephClusterSpec:
      network:
        provider: host
        connections:
          compression:
            enabled: false
      crashCollector:
        disable: false
      dashboard:
        enabled: true
        urlPrefix: /
        ssl: true
      placement:
        mgr:
          modules:
            - name: rook
              enabled: true
          tolerations:
            - effect: NoSchedule
              key: node-role.kubernetes.io/control-plane
      storage:
        useAllNodes: false
        useAllDevices: false
        nodes:
          - name: droplet-2
            devices:
              - name: /dev/disk/by-id/ata-TEAM_T253X2002T_AA000000000000000204
                config:
                  osdsPerDevice: "1"
                  primaryAffinity: ".33"
          - name: droplet-4
            devices:
              - name: /dev/disk/by-id/ata-Patriot_P210_2048GB_PBEADBB2211180808
                config:
                  osdsPerDevice: "1"
                  primaryAffinity: ".33"
          - name: droplet-5
            devices:
              - name: /dev/disk/by-id/ata-Patriot_P210_2048GB_PBEADBB2211180869
                config:
                  osdsPerDevice: "1"
                  primaryAffinity: ".33"
          - name: droplet-6
            devices:
              - name: /dev/disk/by-id/ata-Patriot_P210_2048GB_PBEADBB2211180711
                config:
                  osdsPerDevice: "1"
                  primaryAffinity: ".33"
          - name: droplet-7
            devices:
              - name: /dev/disk/by-id/ata-WDC_WD120EDAZ-11F3RA0_5PJD7E9F
                config:
                  osdsPerDevice: "1"
                  primaryAffinity: "0"
          - name: droplet-oneiros
            devices:
              - name: /dev/disk/by-id/nvme-INTEL_SSDPEDME016T4S_CVMD510400NG1P6KGN
                config:
                  osdsPerDevice: "2"
                  primaryAffinity: "1"
    cephBlockPools:
      - name: ceph-blockpool
        spec:
          failureDomain: host
          replicated:
            size: 3
        storageClass:
          enabled: true
          name: ceph-block
          isDefault: true
          reclaimPolicy: Delete
          allowVolumeExpansion: true
          parameters:
            imageFormat: "2"
            imageFeatures: layering
            csi.storage.k8s.io/provisioner-secret-name: rook-csi-rbd-provisioner
            csi.storage.k8s.io/provisioner-secret-namespace: rook-ceph
            csi.storage.k8s.io/controller-expand-secret-name: rook-csi-rbd-provisioner
            csi.storage.k8s.io/controller-expand-secret-namespace: rook-ceph
            csi.storage.k8s.io/node-stage-secret-name: rook-csi-rbd-node
            csi.storage.k8s.io/node-stage-secret-namespace: rook-ceph
            csi.storage.k8s.io/fstype: ext4
    cephFileSystems:
      - name: ceph-filesystem
        spec:
          metadataPool:
            replicated:
              size: 3
          dataPools:
            - failureDomain: host
              replicated:
                size: 3
              name: data0
          metadataServer:
            activeCount: 1
            activeStandby: true
            resources:
              requests:
                cpu: 1000m
                memory: 4Gi
              limits:
                memory: 4Gi
        storageClass:
          enabled: true
          isDefault: false
          name: ceph-filesystem
          pool: data0
          reclaimPolicy: Delete
          allowVolumeExpansion: true
          parameters:
            csi.storage.k8s.io/provisioner-secret-name: rook-csi-cephfs-provisioner
            csi.storage.k8s.io/provisioner-secret-namespace: rook-ceph
            csi.storage.k8s.io/controller-expand-secret-name: rook-csi-cephfs-provisioner
            csi.storage.k8s.io/controller-expand-secret-namespace: rook-ceph
            csi.storage.k8s.io/node-stage-secret-name: rook-csi-cephfs-node
            csi.storage.k8s.io/node-stage-secret-namespace: rook-ceph
            csi.storage.k8s.io/fstype: ext4
    cephObjectStores:
      - name: ceph-objectstore
        spec:
          metadataPool:
            failureDomain: host
            replicated:
              size: 3
          dataPool:
            failureDomain: host
            erasureCoded:
              dataChunks: 2
              codingChunks: 1
          preservePoolsOnDelete: true
          gateway:
            type: s3
            port: 80
            instances: 1
          healthCheck:
            bucket:
              interval: 60s
        storageClass:
          enabled: true
          name: ceph-bucket
          reclaimPolicy: Delete
          parameters:
            region: us-east-1
