---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: rook-ceph-cluster
  namespace: rook-ceph
spec:
  interval: 15m
  chart:
    spec:
      chart: rook-ceph-cluster
      version: v1.10.11
      sourceRef:
        kind: HelmRepository
        name: rook-ceph
        namespace: flux-system
  maxHistory: 3
  install:
    createNamespace: true
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
  uninstall:
    keepHistory: false
  values:
    monitoring:
      enabled: true
      createPrometheusRules: true
    toolbox:
      enabled: true
    configOverride: |
      [global]
      bdev_enable_discard = auto
      bdev_async_discard = auto
    cephClusterSpec:
      network:
        provider: host
        connections:
          compression:
            enabled: false
      crashCollector:
        disable: true
      cleanupPolicy:
        # confirmation: "yes-really-destroy-data"
        sanitizeDisks:
          method: quick
          dataSource: zero
        allowUninstallWithVolumes: true
      dashboard:
        enabled: true
        urlPrefix: /
        ssl: true
      placement:
        mgr:
          modules:
            - name: rook
              enabled: true
        #   tolerations:
        #     - effect: NoSchedule
        #       key: node-role.kubernetes.io/control-plane
        # mon:
        #   tolerations:
        #     - effect: NoSchedule
        #       key: node-role.kubernetes.io/control-plane
      removeOSDsIfOutAndSafeToRemove: true
      priorityClassNames:
        mon: system-node-critical
        osd: system-node-critical
        mgr: system-cluster-critical
      # cluster level storage configuration
      storage:
        useAllNodes: false
        useAllDevices: false
        encryptedDevice: "false" # the default value for this option is "false"
        nodes:
          - name: droplet-2
            devices:
              - name: /dev/disk/by-id/ata-TEAM_T253X2002T_AA000000000000000204
                config:
                  osdsPerDevice: "1"
          - name: droplet-4
            devices:
              - name: /dev/disk/by-id/ata-Patriot_P210_2048GB_PBEADBB2211180808
                config:
                  osdsPerDevice: "1"
          - name: droplet-5
            devices:
              - name: /dev/disk/by-id/ata-Patriot_P210_2048GB_PBEADBB2211180869
                config:
                  osdsPerDevice: "1"
          - name: droplet-6
            devices:
              - name: /dev/disk/by-id/ata-Patriot_P210_2048GB_PBEADBB2211180711
                config:
                  osdsPerDevice: "1"
          - name: droplet-7
            devices:
              - name: /dev/disk/by-id/ata-WDC_WD120EDAZ-11F3RA0_5PJD7E9F
                config:
                  osdsPerDevice: "1"
          - name: droplet-oneiros
            devices:
              - name: /dev/disk/by-id/nvme-INTEL_SSDPEDME016T4S_CVMD510400NG1P6KGN
                config:
                  osdsPerDevice: "2"
    ingress:
      dashboard:
        enabled: true
        ingressClassName: nginx
        annotations:
        # If the dashboard has ssl: true the following will make sure the NGINX Ingress controller can expose the dashboard correctly
        # nginx.ingress.kubernetes.io/backend-protocol: "HTTPS"
        # nginx.ingress.kubernetes.io/server-snippet: |
        #   proxy_ssl_verify off;
          nginx.ingress.kubernetes.io/whitelist-source-range: |
            10.0.0.0/8,172.16.0.0/12,192.168.0.0/16
          external-dns.alpha.kubernetes.io/target: "ipv4.rengo.dev"
          external-dns.home.arpa/enabled: "false"
          # cert-manager.io/cluster-issuer: letsencrypt-production
          hajimari.io/appName: "Rook"
          hajimari.io/icon: mdi:chess-rook
        hosts:
          - host: &host rook.rengo.dev
            path: /
            # path: "/ceph-dashboard(/|$)(.*)"
        tls:
          - hosts:
              - *host
            secretName: rook-ceph-dashboard-tls

    cephBlockPoolsVolumeSnapshotClass:
      enabled: false
    cephBlockPools:
      - name: ceph-fastpool
        spec:
          enableRBDStats: true
          failureDomain: host
          replicated:
            size: 2
          deviceClass: nvme
        storageClass:
          enabled: true
          name: ceph-fastblock
          isDefault: false
          reclaimPolicy: Delete
          allowVolumeExpansion: true
          parameters:
            imageFormat: "2"
            imageFeatures: layering
            csi.storage.k8s.io/provisioner-secret-name: rook-csi-rbd-provisioner
            csi.storage.k8s.io/provisioner-secret-namespace: rook-ceph
            csi.storage.k8s.io/controller-expand-secret-name: rook-csi-rbd-provisioner
            csi.storage.k8s.io/controller-expand-secret-namespace: rook-ceph
            csi.storage.k8s.io/node-stage-secret-name: rook-csi-rbd-node
            csi.storage.k8s.io/node-stage-secret-namespace: rook-ceph
            csi.storage.k8s.io/fstype: ext4
      - name: builtin-mgr
        spec:
          name: .mgr
          enableRBDStats: true
          failureDomain: host
          replicated:
            size: 3
          parameters:
            compression_mode: none
        storageClass:
          enabled: false
      - name: ceph-blockpool
        spec:
          enableRBDStats: true
          failureDomain: osd
          erasureCoded:
            dataChunks: 2
            codingChunks: 1
          deviceClass: ssd
        storageClass:
          enabled: true
          name: ceph-block
          isDefault: true
          reclaimPolicy: Delete
          allowVolumeExpansion: true
          mountOptions: []
          parameters:
            imageFormat: "2"
            imageFeatures: layering
            csi.storage.k8s.io/provisioner-secret-name: rook-csi-rbd-provisioner
            csi.storage.k8s.io/provisioner-secret-namespace: rook-ceph
            csi.storage.k8s.io/controller-expand-secret-name: rook-csi-rbd-provisioner
            csi.storage.k8s.io/controller-expand-secret-namespace: rook-ceph
            csi.storage.k8s.io/node-stage-secret-name: rook-csi-rbd-node
            csi.storage.k8s.io/node-stage-secret-namespace: rook-ceph
            csi.storage.k8s.io/fstype: ext4

    cephFileSystems:
      - name: ceph-fastsystem
        spec:
          metadataPool:
            enableRBDStats: true
            replicated:
              size: 3
          dataPools:
            - failureDomain: host
              enableRBDStats: true
              replicated:
                size: 2
              name: fast-data0
              deviceClass: nvme
          metadataServer:
            activeCount: 1
            activeStandby: true
            resources:
              requests:
                cpu: 1000m
                memory: 4Gi
              limits:
                cpu: 2000m
                memory: 4Gi
            priorityClassName: system-cluster-critical
        storageClass:
          enabled: true
          isDefault: false
          name: ceph-fastsystem
          pool: fast-data0
          reclaimPolicy: Delete
          allowVolumeExpansion: true
          parameters:
            csi.storage.k8s.io/provisioner-secret-name: rook-csi-cephfs-provisioner
            csi.storage.k8s.io/provisioner-secret-namespace: rook-ceph
            csi.storage.k8s.io/controller-expand-secret-name: rook-csi-cephfs-provisioner
            csi.storage.k8s.io/controller-expand-secret-namespace: rook-ceph
            csi.storage.k8s.io/node-stage-secret-name: rook-csi-cephfs-node
            csi.storage.k8s.io/node-stage-secret-namespace: rook-ceph
            csi.storage.k8s.io/fstype: ext4
      - name: ceph-filesystem
        spec:
          metadataPool:
            enableRBDStats: true
            replicated:
              size: 3
          dataPools:
            - failureDomain: host
              enableRBDStats: true
              replicated:
                size: 3
              name: data1
              deviceClass: ssd
          metadataServer:
            activeCount: 1
            activeStandby: true
            resources:
              requests:
                cpu: 1000m
                memory: 4Gi
              limits:
                cpu: 2000m
                memory: 4Gi
            priorityClassName: system-cluster-critical
        storageClass:
          enabled: true
          isDefault: false
          name: ceph-filesystem
          pool: data1
          reclaimPolicy: Delete
          allowVolumeExpansion: true
          parameters:
            csi.storage.k8s.io/provisioner-secret-name: rook-csi-cephfs-provisioner
            csi.storage.k8s.io/provisioner-secret-namespace: rook-ceph
            csi.storage.k8s.io/controller-expand-secret-name: rook-csi-cephfs-provisioner
            csi.storage.k8s.io/controller-expand-secret-namespace: rook-ceph
            csi.storage.k8s.io/node-stage-secret-name: rook-csi-cephfs-node
            csi.storage.k8s.io/node-stage-secret-namespace: rook-ceph
            csi.storage.k8s.io/fstype: ext4

    cephObjectStores:
      - name: ceph-objectstore
        spec:
          metadataPool:
            enableRBDStats: true
            failureDomain: host
            replicated:
              size: 2
            deviceClass: ssd
          dataPool:
            enableRBDStats: true
            failureDomain: host
            replicated:
              size: 2
              hybridStorage:
                primaryDeviceClass: ssd
                secondaryDeviceClass: hdd
            # erasureCoded:
            #   dataChunks: 2
            #   codingChunks: 1
          preservePoolsOnDelete: false
          gateway:
            type: s3
            port: 80
            hostNetwork: false
            instances: 1
          healthCheck:
            bucket:
              interval: 60s
        storageClass:
          enabled: true
          name: ceph-bucket
          reclaimPolicy: Delete
          parameters:
            region: us-east-1
