---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: rook-ceph
resources:
  # - ./pvols-droplet-3.yaml
  # - ./pvols-droplet-4.yaml
  # - ./pvols-droplet-5.yaml
  - ./helmrelease.yaml
labels:
  - pairs:
      app.kubernetes.io/name: rook-ceph-cluster
      app.kubernetes.io/instance: rook-ceph-cluster
      app.kubernetes.io/part-of: rook-ceph
