---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: cluster-apps-piraeus
  namespace: flux-system
spec:
  interval: 15m0s
  path: ./kubernetes/apps/piraeus-datastore/piraeus/app
  prune: true
  sourceRef:
    kind: GitRepository
    name: home-kubernetes
    namespace: flux-system

---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: cluster-apps-piraeus-resources
  namespace: flux-system
spec:
  dependsOn:
    - name: cluster-apps-piraeus
  interval: 15m0s
  path: ./kubernetes/apps/piraeus-datastore/piraeus/resources
  prune: true
  sourceRef:
    kind: GitRepository
    name: home-kubernetes
    namespace: flux-system
