---
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: hdd-lvm
allowVolumeExpansion: true
provisioner: local.csi.openebs.io
parameters:
  storage: "lvm" # unsure if this is required
  vgpattern: "lvmvg.hdd"
  thinProvision: "yes"
volumeBindingMode: WaitForFirstConsumer
allowedTopologies:
  - matchLabelExpressions:
      - key: openebs.io/nodename
        values:
          - droplet-0
          - droplet-7
