---
apiVersion: ceph.rook.io/v1
kind: CephObjectStoreUser
metadata:
  name: rengo
  namespace: rook-ceph
spec:
  store: ceph-objectstore
  displayName: rengo
  capabilities:
    users: "*"
    bucket: "*"
    usage: "*"
    metadata: "*"
    zone: "*"
