---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ./namespace.yaml
  - ./kubernetes-dashboard/ks.yaml
  - ./smartctl-exporter/ks.yaml
 # - ./kube-prometheus-stack/ks.yaml
 # - ./thanos/ks.yaml
 # - ./grafana/ks.yaml
