---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: cells
  namespace: hosted
spec:
  chart:
    spec:
      chart: cells
      reconcileStrategy: ChartVersion
      sourceRef:
        kind: HelmRepository
        name: cells
        namespace: flux-system
  interval: 15m0s
  values:
    env:
      - name: CELLS_KEYRING
        value: vault://vault.vault.svc:8200/secret?key=master

    service:
      type: ClusterIP
      # port: 8080
      # discoveryPort: 8002
      # binds:
        # Set values here if you want to bind the port elsewhere
      # reverseproxyurl: cells.rengo.dev
      # tlsconfig:
        # selfsigned:

    ingress:
      enabled: false

    #------------------------------
    # Dependency settings
    #------------------------------
    mariadb:
      enabled: true
      volumePermissions:
        enabled: true

    redis:
      enabled: true
      volumePermissions:
        enabled: true
      auth:
        enabled: false
      persistence:
        storageClass: ceph-filesystem
        accessModes: ["ReadWriteMany"]
      # replica:
      #   persistence:
      #     storageClass: ceph-filesystem
      #     accessModes: ["ReadWriteMany"]

    nats:
      enabled: true
      auth:
        enabled: false
      volumePermissions:
        enabled: true

    etcd:
      enabled: true
      commonAnnotations: {
        "helm.sh/hook": "pre-install",
        "helm.sh/hook-weight": "-2"
      }
      auth:
        rbac:
          create: false
      volumePermissions:
        enabled: true

    minio:
      enabled: true
      defaultBuckets: "thumbnails pydiods1 personal versions cellsdata binaries"
      persistence:
        storageClass: ceph-block
        size: 10Gi
      volumePermissions:
        enabled: true
      auth:
        # existingSecret: cells-minio
        # auth.forceNewKeys: true

    mongodb:
      enabled: true
      auth:
        enabled: false
      volumePermissions:
        enabled: true

    vault:
      enabled: false
      # global:
      #   tlsDisable: true
      # injector:
      #   loglevel: debug
      #   allowPrivilegeEscalation: true
      #   annotations: {
      #     "helm.sh/hook": "pre-install",
      #     "helm.sh/hook-weight": "-3"
      #   }
      #   webhook:
      #     annotations: {
      #       "helm.sh/hook": "pre-install",
      #       "helm.sh/hook-weight": "-3"
      #     }
      #     failurePolicy: Ignore
      #     namespaceSelector:
      #       matchExpressions:
      #         - key: kubernetes.io/metadata.name
      #           operator: NotIn
      #           values: ["rook-ceph", "monitoring", "networking", "calico-system", "tigera-operator", "flux-system", "vault", "kube-system", "kube-public", "kube-node-lease"]
      # server:
      #   annotations: {
      #     "helm.sh/hook": "pre-install",
      #     "helm.sh/hook-weight": "-3"
      #   }
      #   dataStorage:
      #     storageClass: ceph-block
      #     mountPath: /tmp/vault/data
      #   volumePermissions:
      #   enabled: true
      #   extraVolumes:
      #     - type: configMap
      #       name: cells-vault
      #   postStart:
      #     - "/bin/sh"
      #     - "-c"
      #     - "sleep 5 && cp /vault/userconfig/cells-vault/bootstrap.sh /tmp/bootstrap.sh && chmod +x /tmp/bootstrap.sh && /tmp/bootstrap.sh"
      # statefulset:
      #   annotations: {
      #     "helm.sh/hook": "pre-install",
      #     "helm.sh/hook-weight": "-3"
      #   }
