# yamllint disable
kind: Secret
apiVersion: v1
metadata:
    name: cells-minio
    namespace: hosted
    labels:
        app.kubernetes.io/name: minio
        helm.sh/chart: minio-11.10.3
        app.kubernetes.io/instance: cells
        app.kubernetes.io/managed-by: Helm
type: Opaque
data:
    root-user: ENC[AES256_GCM,data:M/4aUOwjMFs=,iv:V/Dt1MaJANe1MXw6sdiR96dJ/xrZQnten3dbBRrssjE=,tag:+3StpAwfVoCBM/Qq4xyTAA==,type:str]
    root-password: ENC[AES256_GCM,data:6Gr+K+y0BMfUEB0xxJiWbg==,iv:4ijWQI5zQRARSwupHTPyUho6NfnsrhdTUAC0V9xAmFE=,tag:V4tsr06nE7jvfUEGKHrsVA==,type:str]
    key.json: ""
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1utfeyvqq4ayjnc5ap5ymst4zv008vw3eltpp9cejz3hy4yvnascqxjxn09
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBWeVhGR05sZXpNdTcweGxz
            OWZzMHArQ1FNTEViZ1NoemxTNWdiRVFtcURBCnFHNEtnemp2TWdKL2phV3ZvOGNH
            emcrUytJRUl6STNCKzVjVHl5bkxIT2MKLS0tIEdrbkEwYkl4ODh0Ky9TakJBMWty
            aTh6cU9xcjBRZWxVc1dyU3hrM200UjgKFanc04JcpS4vZUn24QQg+HxVo2c1la7J
            KK/TkNIPCILXeHuyt5gK4QeRzsb3SRgqRlH1yKaX46GfhU2aBHwviw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-03-22T22:49:34Z"
    mac: ENC[AES256_GCM,data:2CrYnTXkwcDeo05JjD4y3LMC9xYVe+Wp5E896CohbAabsN5DEe1WDuPwEJCdxt1NGMNCOD2X+u+wZOIJ3Gkx8A0eDA2dUBi0d9cXFC6Ti3qKAUmdnL2Nk8PLJ9No3gBlGLypdyNdSdZ4trfZPSaAoszYS6sAFWAdBpTz2Z1AAHs=,iv:2VwWxbxwW+LWuOUP7YvBBu4Ic1jvsio0eeSgy/zX/Kk=,tag:d5ygi9EOv0V/gIekNVDClw==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
