---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: xbackbone
  namespace: default
spec:
  interval: 15m
  chart:
    spec:
      chart: app-template
      # -- Version of the app-template helm chart
      # this example is not automatically updated, so be sure to use the latest chart version
      version: 0.1.1
      interval: 15m
      sourceRef:
        kind: HelmRepository
        name: bjw-s
        namespace: flux-system

  values:
    image:
      # -- https://hub.docker.com/r/linuxserver/xbackbone/
      repository: linuxserver/xbackbone
      pullPolicy: IfNotPresent
      tag: 3.6.1

    strategy:
      type: Recreate

    configMaps:
      config:
        enabled: true
        labels: {}
        annotations: {}
        data:
          config.php: |-
            <?php

            return [
                'base_url' => 'https://localhost', // no trailing slash
                'db'       => [
                    'connection' => 'sqlite',
                    'dsn'        => realpath(__DIR__).'/resources/database/xbackbone.db',
                    'username'   => null,
                    'password'   => null,
                ],
                'storage' => [
                    'driver' => 's3',
                    'endpoint' => 'http://rook-ceph-rgw-ceph-objectstore.rook-ceph.svc:80',
                    'key' => 'AYDGPH6G5HV2KGKWVU42',
                    'secret' => 'nGv3BaMmczN7vGEjspjJJ4NqGm8B8s5oASwgX7nA',
                    'region' => 'us-east-1',
                    'bucket' => 'xbackbone',
                ],
            ];

    env:
      PUID: 1000
      PGID: 1000
      TZ: America/New_York


    # -- Configures service settings for the chart.
    service:
      main:
        ports:
          http:
            port: 80

    ingress:
      # -- Enable and configure ingress settings for the chart under this key.
      main:
        enabled: true
        ingressClassName: nginx
        hosts:
          - host: &host files.rengo.dev
            paths:
              - path: /
                pathType: Prefix
                service:
                  port: http
        tls:
          - secretName: xbackbone-tls
            hosts:
              - *host

    # -- Configure persistence settings for the chart under this key.
    persistence:
      config:
        enabled: true
        type: configMap
        name: config
        mountPath: /config
