apiVersion: v1
kind: Secret
metadata:
    name: external-dns-secret
    namespace: networking
stringData:
    email: ENC[AES256_GCM,data:UzWbC2NWq73gnfSZMzim,iv:7OrVEEkrL8AHK0yrEc9EsymjdMmFr/JcAio2azUbaRI=,tag:RJZeXMpXufW2tIYf8YP0pw==,type:str]
    api-key: ENC[AES256_GCM,data:mNz0M14IcindRBEl2sv1WOSZ82z8pqWZQ0xENZj0BO6i4wDHMQ==,iv:YmhoprCI+VD6pkXWbpUlv1PCaJwKxqYiSAkzimFehcA=,tag:P5k6SAzwbG9Ubts0faNMJw==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1utfeyvqq4ayjnc5ap5ymst4zv008vw3eltpp9cejz3hy4yvnascqxjxn09
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBoeld2dDhJc2hKdkxGaDdn
            d2NVU2ZrVHVNR0xoTlgxNXl4V2g1ZDBUU3pFCkFhVitBMGVIVEpvRHhSZXRxQWdG
            QTZLT1I5UStGRmgxRzRCWG85WGhpaDgKLS0tIEN2SlVIT2E5L1VkV2EvRTF2QjhG
            dkF2anI2UW1jQjNTQitaOVZ4MG5Pc00KlAk8JGsrAzXMh9NafAPhaRzMFde6Zz/P
            PeSLZpwQygj+O1XNer/RdMMC/8FCTp9SVetuYwMF90z0NP8Xd3I9wQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-01-20T20:46:37Z"
    mac: ENC[AES256_GCM,data:pWFjrJaHQS7Dfulk/XXmTiCQ1DqS0OaSdRUKFmAFmB8GnGj58wygMSVfOZbTVNJAtH7eEaqdM6rbxiRLSQkr/fePAWMxr4lRqFc//fc1q3tFxTTwco2VIGMSWzQ5Km91uiKuHrQlPoCIiO8r3Ik3PURp2f6U3RBZFFdZ21t45aA=,iv:3lTOQzAd1X1XeDapffFNSM4MoY6r0HBuaABRiTF40CA=,tag:Cpd3OyxjpGaMMkdxVDnkaA==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
