apiVersion: v1
kind: Secret
metadata:
    name: external-dns-secret
    namespace: networking
stringData:
    email: ENC[AES256_GCM,data:025bw1hX1uOr1qpEFleY,iv:2WCrXmJSaRP3L97iz+6EVtyBmRjzdKL7L2rTjF4x9Og=,tag:5Eq22/+pCerzv/lABN11fQ==,type:str]
    api-key: ENC[AES256_GCM,data:/0n5PBTwTbqAqiW6Wb29gqXv/5z8biA+1i1H0yTokNkPDsJMoQ==,iv:ZoBbgMH4xC5Yiuk2UdZS9Xi1TKXHvknru0/whEnY1D8=,tag:uRuz1IkdX1MzSXFg5SV4PQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1utfeyvqq4ayjnc5ap5ymst4zv008vw3eltpp9cejz3hy4yvnascqxjxn09
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB0aFYvVFVyNWhTeDRNVEs4
            K2dKeFMxL2p1anFZSEovdGEzQXBacjNtK2lrClhtSC9iSHcrU0puQmFSdyt5QVI1
            Vm9BdDBReGVvTzgzSWJLU3NEd1A5N00KLS0tIG1RK3pFck9FLzU1eWpqRVhKdGc4
            aXdGL0crU3h0VHo5WEMvbEI5NS9WV0EKyxEtWMmQHJ/nYVe3LT2P32x5CRPs/PBt
            Zfv/bfTIz8q6SveQfJB4u0goYGt/lgjtbkV2XQE6Db4WsHRgvfAXfQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-02-22T02:56:50Z"
    mac: ENC[AES256_GCM,data:DM7IVMf+O/QfN7KfDSYniptiNlmysXVzdh4RbQinYegqZv3xs2Ql/ChyeQeUL3SoNXrsx7b8+HktceLqVWxsvFEjmAqOo6vDI4EctgcPPbmfheqwRJ0wMFuOj/Gsn/ZpTR2MhOoH10e3qej8NZKIkXhndkV/WM43j1aveWfNDPg=,iv:co5++OLKZa7pDnRjJgNKzjWvKMnxfm/7naBF6W7z0aw=,tag:PZFfd04MVC6XinA6eq8uXg==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
