apiVersion: v1
kind: Secret
metadata:
    name: external-dns-secret
    namespace: networking
stringData:
    email: ENC[AES256_GCM,data:ic7I7hY15acrkTwyvfBg,iv:43xBbUVF3UCkAW9hNjdNUs5cJskNgoMDsWekqZAK04c=,tag:NnoHFsFAV1GdWUKx35u0hA==,type:str]
    api-key: ENC[AES256_GCM,data:7/Q+xPFwMIUkMHFO5zNCu2BCqo+u67k6xAe50WdKiCaJO8VQkw==,iv:dkXFsAW7m2L4QIUyLgUeUptzWuag9U0IFZDBwSBOgzM=,tag:K85fy9GL23vfkfsNRnb3XQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1utfeyvqq4ayjnc5ap5ymst4zv008vw3eltpp9cejz3hy4yvnascqxjxn09
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA5Z3ZoWGU3dFFrdjZDby8w
            Q3hBVzdNMTFCaEFBNVJ0dHY3cG0ydWJBc2s4CnUxbVgzbnJCbHhlRlVtM2x5bWR4
            QW9FVGZ2Ty80bmtJaGgydFQzajdUVVkKLS0tIEpwNGRoZUNFdzdHOTFDTjlnVXpx
            TkNQZDgwK1BYM1RsdTYwUEoxNFZwQjgKzeHa/VH1ttGY/2Jo7HeuLeGoi6bVcEoX
            MUxQuTFHnsVGrYF1XgFW/XNXWVhWKZs6/iQPfQ3rb9EHhA6dGOUUjQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-01-18T01:44:41Z"
    mac: ENC[AES256_GCM,data:kLkPPRORbwWio/plylHXcagqGkuykTh8eykEgVbFYxTX7MNnKPmDgJpPPUFmIVFArUwJa1t1jloZ2KneQnNAfTkiGnJaoTdMEX6xgEn9ZumL2V0zAwkaXUOLdqs31lsd274aQGPE0Z5Q44w4/6SnPX0rIptPatJ8nzxnTGE9Uec=,iv:OvRRzjHJKamhrAWdazoNLC1Vs5V5GT1oOruM5Wxjp3M=,tag:0HJ9nNgKjvT3z9aQX4Adxw==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
