---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: ndm
  namespace: openebs
spec:
  chart:
    spec:
      chart: openebs-ndm/openebs-ndm
      reconcileStrategy: ChartVersion
      sourceRef:
        kind: HelmRepository
        name: openebs-ndm
        namespace: flux-system
  interval: 15m0s
values:
  analytics:
    enabled: false
