---
- hosts:
    - droplet-2
    - droplet-3
    - droplet-4
    - droplet-5
    - droplet-6
  become: true
  gather_facts: true
  any_errors_fatal: true
  vars_prompt:
    - name: nuke
      prompt: |-
        Are you sure you hate ceph?
        Type YES
      default: "n"
      private: false
  pre_tasks:
    - name: Check for confirmation
      ansible.builtin.fail:
        msg: Aborted
      when: nuke != 'YES'

    - name: Pausing for 5 seconds...
      ansible.builtin.pause:
        seconds: 5

    - name: Wipe disklabel
      command: sgdisk --zap-all {{ item }}
      with_items: "{{ disks }}"

    - name: discard device
      command: blkdiscard {{ item }}
      failed_when: False
      with_items: "{{ disks }}"

    - name: probe partitions
      command: partprobe {{ item }}
      with_items: "{{ disks }}"

    - name: Delete var/iib/rook
      ansible.builtin.file:
        path: /var/lib/rook
        state: absent
