---
- hosts:
    - master
    - worker
  become: true
  gather_facts: true
  any_errors_fatal: true
  pre_tasks:
    - name: Pausing for 2 seconds by rolling out rebootz...
      ansible.builtin.pause:
        seconds: 2
  tasks:
    - name: Reboot
      ansible.builtin.reboot:
        msg: Rebooting nodes one by one
        reboot_timeout: 3600
      throttle: 1
