---
- hosts:
    - master
    - worker
  become: true
  gather_facts: true
  any_errors_fatal: true
  pre_tasks:
    - name: Pausing for 2 seconds before rebooting only if needed...
      ansible.builtin.pause:
        seconds: 2
  tasks:
    - name: Check for Reboot
      stat:
        path: /var/run/reboot-required
      register: reboot_required
    - name: Reboot
      ansible.builtin.reboot:
        msg: Rebooting nodes
        reboot_timeout: 3600
      throttle: 1
      when: reboot_required is defined and reboot_required.stat.exists
