---
- hosts:
    - droplet-0
    # - droplet-3
    # - droplet-4
    # - droplet-5
    - droplet-7
  become: true
  gather_facts: true
  any_errors_fatal: true

  pre_tasks:

    # - name: Create a new primary partition for LVM
    #   community.general.parted:
    #     device: "{{ item }}"
    #     flags: [ lvm ]
    #     state: present
    #   with_items: "{{ disks }}"

    # - name: Create a volume group on top of nvme disks
    #   community.general.lvg:
    #     vg: lvmvg.nvme
    #     pvs: /dev/nvme0n1

    # - name: Create a volume group on top of SSD disks
    #   community.general.lvg:
    #     vg: lvmvg.ssd
    #     pvs: /dev/sdb

    - name: Create a volume group on top of nvme disks
      community.general.lvg:
        vg: lvmvg.hdd
        pvs: /dev/sdb
