---
- hosts:
    - droplet-0
    # - droplet-1
    # - droplet-2
    - droplet-3
    - droplet-4
    - droplet-5
    # - droplet-6
    - droplet-7
    # - droplet-oneiros
  become: true
  gather_facts: true
  any_errors_fatal: true
  vars_prompt:
    - name: nuke
      prompt: |-
        Are you sure you hate your data?
        Type y
      default: "n"
      private: false
  pre_tasks:
    - name: Check for confirmation
      ansible.builtin.fail:
        msg: Aborted
      when: nuke != 'y'

    - name: Pausing for 5 seconds...
      ansible.builtin.pause:
        seconds: 5

    - name: Wipe disklabel
      command: sgdisk --zap-all {{ item }}
      with_items: "{{ disks }}"

    - name: discard device
      command: blkdiscard {{ item }}
      failed_when: False
      with_items: "{{ disks }}"

    - name: probe partitions
      command: partprobe {{ item }}
      with_items: "{{ disks }}"

    - name: Delete var/lib/rook
      ansible.builtin.file:
        path: /var/lib/rook
        state: absent

    - name: Delete var/openebs
      ansible.builtin.file:
        path: /var/openebs
        state: absent

    - name: Delete var/lib/rancher/k3s/storage
      ansible.builtin.file:
        path: /var/lib/rancher/k3s/storage
        state: absent
