---
- hosts:
    - master
    - worker
  become: true
  gather_facts: true
  any_errors_fatal: true
  vars_prompt:
    - name: nuke
      prompt: |-
        Are you sure you hate ceph?
        Type YES
      default: "n"
      private: false
  pre_tasks:
    - name: Check for confirmation
      ansible.builtin.fail:
        msg: Aborted
      when: nuke != 'YES'

    - name: Pausing for 5 seconds...
      ansible.builtin.pause:
        seconds: 5

    - name: Delete var/iib/rook
      ansible.builtin.file:
        path: /var/lib/rook
        state: absent
