apiVersion: v1
kind: Secret
metadata:
    name: weave-gitops-secret
    namespace: flux-system
type: Opaque
stringData:
    adminPassword: ENC[AES256_GCM,data:YW9htVAdVlaZ5xuCvboa+2vOlsriIJGdhV0KSCXwt6BoTo8B/kd3eszlr6d6t3DH6la1WQ9+kf7yNkf1,iv:mxhfpN8ymgv8neGoN0J9Ts+gC2m/S0pWAeG5wtrQyLs=,tag:aa3SyZzcqI5IN1xdyES23g==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1utfeyvqq4ayjnc5ap5ymst4zv008vw3eltpp9cejz3hy4yvnascqxjxn09
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBsN2dwWk5NRlRkbGxaU3dN
            S2dWRUhEWXU5UDlCb0RhQlBlUHlVM3ppVjFFClhTMk9icnFaM2xtbjlWeERQSUdY
            Y1daaDdYeC9MM1cyU0VzaSs1Z3ZnRGcKLS0tIDg1TzVwRUpDTnk1Q0NKSk1tOXNr
            S25ReUcvNjY3VTdPREc5MlNqbnZ6M0UKnp0gPoZaWlCM0NvAWYRR1hnXq3MGAfmw
            +7cwGsxah4dA8rOje7ap+CILmDNAfcDSAPspfSaZxBCWSg7TaQwcBA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-01-20T22:17:28Z"
    mac: ENC[AES256_GCM,data:yPQp9cW5hI5IBK1U4pcEUuM0nZFwciLvQ3dnaP7CwbUEQzVNpMHpY9kHE4mljk05a9DIA0pEf+dYj7CxINsQ4pSs/pPBhg6sHHZnDZWiJwhk389T15YUeNh1bu4azyQwW0s5yDEYnndlKxYYJJc3ugFLEE/AOWl4J3s7MlXe6Xw=,iv:Xvy5JMyLLOt7nSlaAgpTRyUy0UO9BD4ohcQnjyebUwo=,tag:EdbzeXPlGhfciT8xrL633Q==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
