apiVersion: v1
kind: Secret
metadata:
    name: weave-gitops-secret
    namespace: flux-system
type: Opaque
stringData:
    adminPassword: ENC[AES256_GCM,data:jAJ6ZZE00pEmZAJqWBS2im7P3ag3e70UlLiPXVJkF7IPHLISTFaqTBdtOvoLzOCm43jolnxVUYzBnRVs,iv:1FkjjOVdkXlOkY9l+lZdxMInxjP09V3tYFlsM7s9jWo=,tag:Z3QVJxmNjMawKll5EN2MYA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1utfeyvqq4ayjnc5ap5ymst4zv008vw3eltpp9cejz3hy4yvnascqxjxn09
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAvdFdPbHNiOUkxNG9wcXhr
            ZFlxb2Z0dytWRDBWdXJFOTN6WWxqYkpvQ2cwCjJuUVlQZ3R5cUkxRkdwY3R3K3hv
            QXlWUFhHVDZTeURNWDlXUG12ZFlQNG8KLS0tIHBjbXloMnJySTlEVDdnRUpGcER6
            NHd4bUtqMURRa2pEZ0U3V3Y5R0ZaQTAKr+Pe7MXXqsdbdypTtoCQmKryDyF+y5rn
            d0lxi0Unh7MXYpLgqXcztQYcrutuCp6RgG0bYBmBbAvIzt1iBF0Stw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-02-22T02:56:50Z"
    mac: ENC[AES256_GCM,data:AyFK8PJmXsrsvHdhOu3vj8fFegfQTHZpiSuJ9I40BmDghJm07cpER3vGSEEq7XOZTWZiAh15f4Hn4+R/cGVG6Hd19ZX0zBZ6ZsJMWJK7PwdczWGMxTdFJjZteeUROi7ppEiP4DMKM6JIm0PEKBpQrxyx/ovw4p+tiLwaXB1yxAE=,iv:0sr97ISS+LYQyP26wilLwkNvUd4+/2feL9lQAqYXVL4=,tag:8jU0PG45+XueHmBgLnFh7Q==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
