apiVersion: v1
kind: Secret
metadata:
    name: weave-gitops-secret
    namespace: flux-system
type: Opaque
stringData:
    adminPassword: ENC[AES256_GCM,data:WTndADc/nIgyPZquB7Y1gN50wJ1J4SdH2XPEUMiNH4/Kp94hJqxUxRveub9UqnOHF4wSDh/4v7VS2Fmb,iv:o/Mowx+5Ex3jV3nbdBgIxCRZt63VECn/J3ZXL/WFla4=,tag:NJLFmgcfM40IosE4KlU9dg==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1utfeyvqq4ayjnc5ap5ymst4zv008vw3eltpp9cejz3hy4yvnascqxjxn09
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBnQkM5TzU1NGJpYnJxdHhN
            dUQ3M1ZCbmVoRVhHbGVRNjhSK2p3a20vNUZrCkFWSkFiWTcrQVpGcHJTaXpyU2s3
            UDJ4Mno2b2IrZEFFQ280QTc4NCt1cXcKLS0tIExqUm9EWHpBWDVMaE9sd1ZsVStZ
            R3pHOCtlTzhUV3BpSXArYzdZTmhBaDAKJRILTDTuK62HGZ2yGH/yAYkUjDjMA/wb
            qbegYUnTKalqmJvlHqPXOaNxxGzkiWuRoRmu8Zt8UYWnME6MpKG1wg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-01-18T01:44:42Z"
    mac: ENC[AES256_GCM,data:3I53RKOGmst1UgCvFz1GcM3jo37bkNloYbLmwDOCBCJtKeaLruUorc2aT4OouvHXlRHXxFGvOLHIkk1YqurozvCW+u3998NLBauZd2c+n2Zl7joaCs6vRi07R+4Q+/SlEtWSo+CNf0owI4/PdFFGEWIVQ+i+VqMiaxazfoMHxMs=,iv:WAJChAeqNlls8cyl1FxW/PojOsddcrxBwfYffWYAYVQ=,tag:fBlwv7fiDvz6cPh438/hAA==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
