apiVersion: v1
kind: Secret
metadata:
    name: weave-gitops-secret
    namespace: flux-system
type: Opaque
stringData:
    adminPassword: ENC[AES256_GCM,data:3d5gved/3Xhp4I0plTWWzbWqPcUSJgLNtREJvp/QJSyBee8W9Ssp5Vff6dX9eF1u,iv:i6KkHZH3/eUla+2qp6+aE/iaf5RQvV1v9ZKPt+vwTWo=,tag:B1FfzAH6pwVq6M8+01SeEw==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1utfeyvqq4ayjnc5ap5ymst4zv008vw3eltpp9cejz3hy4yvnascqxjxn09
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBrOGd3aW5XZ0QxRXQxVC9P
            RG0rcllzL09qMmRUYzlsSnd1Y1E4WVE4NUY4CkhLVFFGSEVxQyswUm9KK0JYV1E0
            R2NYSmI3czU5YWp6SmJLK1VweC9IL0EKLS0tIHMzVFB4cTh2di9IUnQwb1cxZllm
            UjhUUUZMYi93SHJOQjE5VUZnVjNoTjQKM5XHODBxwnS0qYiv4BMJ0ebxMC5/3LPQ
            3BgtLaYfwIFPipmc2/ePV5sRsvRTZNhsYnF9cAOdh90rqRP9lTL3Rg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-01-20T20:25:59Z"
    mac: ENC[AES256_GCM,data:0IuSvNwbuJHKS6RXx6+4EvS3RmzsJhDZxqkYKnYjdF9jx4NYwnlpVwznFpy+kY6y7obeuSJtjpR2to6hbPRHSeZKfcSJEHsu3j7FBu3DX/5LAYcz5kFvZy3xH2GheE1RH20UYpselwdrrNAFON49J8CVSnXT7n23686Ja2sh0dk=,iv:/0upboNXYWm2YyMdagEbOqUejGpKPl592Cg9SOQJxag=,tag:9mSscfkeVN8/z97w14i9PA==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
