apiVersion: v1
kind: Secret
metadata:
    name: weave-gitops-secret
    namespace: flux-system
type: Opaque
stringData:
    adminPassword: ENC[AES256_GCM,data:XI5CQ0WUe2ZpRsj6jtlyQaWWYezbNR/dW/5y6ajocMy0AfumkUNL3kJX70H+Vet7dqjlF3N6RB0Hy5p1,iv:u6zrQzE/OmivyLIGbAvVNSnewDxbL9hswCSTWxNGWXI=,tag:rqoS6YwH5pL81porgGqVQQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1utfeyvqq4ayjnc5ap5ymst4zv008vw3eltpp9cejz3hy4yvnascqxjxn09
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA2aHg0NGVER1hhSlBsYmNj
            QWFnVHFyd25OaElvWUdMalNSZU1Wb28xUVNNClowSXNSWGxGTFhkR2dLZzFyeHlT
            amFNeDdtM2dYL1hZRlpTRDQzUm1BU2MKLS0tIGlzeEljeklseDBHNHdPQWw5dWNH
            OHhBeStHclJHcmRodXZaNkN0T3FmMEUKJIFmPrYC8wAK/1bBuaZK5CGDgejlkqWX
            zB07TUAye0qvpFMrn/Fo7xFPqx0tmsM31krpyhqwRtQKWciJTcpvfA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-01-20T17:41:02Z"
    mac: ENC[AES256_GCM,data:8OIMbwd9/Jm126a/ptp3Cs9tlh90d5X68aWanahkZfbqzQJsAd/1vinZbbA5k9jiX3gmXJg3qMEkjHB6B/zIxJtFGjeuGvZxk1WH9QDRigOJgs9LSF7F2/WS1jyadGfbo9lmEugMWUjj4txzXLzEqBoIKEMv5yz87NVLg9mjm4A=,iv:HwuN5VLVa0gPn+G5Zhc3N6VkMM72yAvlXq87c0NULGE=,tag:0OPeXMNf+LlyXSeoSBX1cg==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
