---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: cluster-apps-openebs-lvmlocalpv
  namespace: flux-system
spec:
  interval: 15m0s
  path: ./kubernetes/apps/openebs/lvmlocalpv/app
  prune: true
  sourceRef:
    kind: GitRepository
    name: home-kubernetes
