---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: cluster-apps-openebs-lvmlocalpv
  namespace: flux-system
spec:
  path: ./kubernetes/apps/openebs/lvmlocalpv/app
  prune: true
  sourceRef:
    kind: GitRepository
    name: home-kubernetes
  healthChecks:
    - apiVersion: helm.toolkit.fluxcd.io/v2beta1
      kind: HelmRelease
      name: openebs-lvmlocalpv
      namespace: openebs
  interval: 30m
  retryInterval: 1m
  timeout: 5m
