---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: nextcloud-main-pvc
  namespace: hosted
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 100Gi
  volumeName: nextcloud-main
  storageClassName: nvme-lvm-5
  volumeMode: Filesystem
