apiVersion: v1
kind: Secret
metadata:
    name: pushover-secrets
    namespace: monitoring
type: Opaque
stringData:
    user-key: ENC[AES256_GCM,data:uD+bMP9jd5ygNeairJ4z4PWjAWlg7g8wTI25MwXY,iv:+FwGPpwry4BFCzrWHFgeqx3qqbk7Bg9ICF8OokQL79E=,tag:HJYuviz8StM9ZKGI0ji7oQ==,type:str]
    token: ENC[AES256_GCM,data:I8BkyoV8npyc2jRX9A+svWuCdWxm+iQVEodmfSWV,iv:PctBundGMaEI0YHc4iL4/wK70CgY+H4gAXajpzQo0ew=,tag:l3XZqOeYG8De5zxPOhEtig==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1utfeyvqq4ayjnc5ap5ymst4zv008vw3eltpp9cejz3hy4yvnascqxjxn09
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB6dGNKbnRVamt5cTZlek9a
            TXZUcURqOVY2SVZkd0lUOEk4TndCaG8rK21NCnNlUW80MzBMYnZRdWpaT0hERWV1
            YmtQUHFyUyt4dHRYdGhndUxMdlVNZDAKLS0tIHVCemU4QkxNa3RTOWJ0cUEvQy93
            WTVNVFhaOXU0MGU0KzRmbmg2Q1hJa2cKhlVqBN+qEeLjiSRdi6Vi3oI3PVqAnbwA
            XmzNA6pxEWSfIuGWNKDWcxdJi6CliBxvMJEkvSHlsBzBrxPSNpsDtw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-02-27T07:07:49Z"
    mac: ENC[AES256_GCM,data:CSQ2YGO8wTam2ZPEp8p+EYLH8fIcxxCsJXNwnFYk9EfDTmGVEd44S3tvJjmdk0PKDVU46rd5r9TvKbo7NJ6/Zl4ZlLo/2uRtEEMDB6lc/dNTPUvrlq3cbtw8IGnr4olv4882wMAEu/7QN3/OvQOZ+CnKy+oLW8iahBri9pYa1W8=,iv:NHvpBHMzOqFij7taXIruAxTgKC+qOTz+5wL4yfz+xXk=,tag:zjAXffaeUufG4cW0TRNQNw==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
