---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: rook-ceph-operator
  namespace: rook-ceph
spec:
  interval: 15m
  chart:
    spec:
      chart: rook-ceph
      version: v1.11.1
      sourceRef:
        kind: HelmRepository
        name: rook-ceph
        namespace: flux-system
  maxHistory: 3
  install:
    createNamespace: true
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
  uninstall:
    keepHistory: false
  values:
    crds:
      enabled: true
    pspEnable: false
    monitoring:
      enabled: true
    csi:
      rbdFSGroupPolicy: "ReadWriteOnceWithFSType"
      cephFSFSGroupPolicy: "ReadWriteOnceWithFSType"
      nfsFSGroupPolicy: "ReadWriteOnceWithFSType"
      provisionerReplicas: 1 # default 2
      # Enables
      enableRbdDriver: true
      enableOMAPGenerator: true
      enableCephfsDriver: true
      enableGrpcMetrics: true
      # Disables
      enableMetadata: false
      enableCSIHostNetwork: false
      enableCephfsSnapshotter: true
      enableNFSSnapshotter: true
      enableRDBSnapshotter: true
      enableCSIEncryption: false
      nfs:
        enabled: true
      topology:
        enabled: false
      readAffinity:
        enabled: true
    enableDiscoveryDaemon: true
    resources:
      requests:
        cpu: 10m
        memory: 128Mi
      limits:
        memory: 512Mi
