---
apiVersion: v1
kind: ConfigMap
metadata:
  name: cluster-settings
  namespace: flux-system
data:
  TIMEZONE: "America/New_York"
  KUBE_VIP_ADDR: "10.13.20.99"
  METALLB_LB_RANGE: "10.13.20.79-10.13.20.89"
  METALLB_K8S_GATEWAY_ADDR: "10.13.20.79"
  METALLB_INGRESS_ADDR: "10.13.20.80"
  METALLB_NFS_ADDR: "10.13.20.81"
  METALLB_TRAEFIK_ADDR: "10.13.20.82"
