---
apiVersion: v1
kind: ConfigMap
metadata:
  name: cluster-settings
  namespace: flux-system
data:
  TIMEZONE: "America/New_York"
  KUBE_VIP_ADDR: "10.13.10.99"
  METALLB_LB_RANGE: "10.13.10.75-10.13.10.95"
  METALLB_K8S_GATEWAY_ADDR: "10.13.10.75"
  METALLB_INGRESS_ADDR: "10.13.10.76"
