---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "direct-pv.fullname" . }}-csi-min-io
  labels:
    application-name: direct.csi.min.io
    application-type: CSIDriver
    direct.csi.min.io/created-by: kubectl-direct-csi
    direct.csi.min.io/version: v1beta5
  {{- include "direct-pv.labels" . | nindent 4 }}
  annotations:
    pod-security.kubernetes.io/enforce: privileged
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "direct-pv.fullname" . }}-csi-min-io
  labels:
    application-name: direct.csi.min.io
    application-type: CSIDriver
    direct.csi.min.io/created-by: kubectl-direct-csi
    direct.csi.min.io/version: v1beta5
  {{- include "direct-pv.labels" . | nindent 4 }}
  annotations:
    pod-security.kubernetes.io/enforce: privileged
    rbac.authorization.kubernetes.io/autoupdate: "true"
spec:
  replicas: {{ .Values.csiMinIo.replicas }}
  selector:
    matchLabels:
      selector.direct.csi.min.io: direct-csi-min-io-1r3j5
    {{- include "direct-pv.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        selector.direct.csi.min.io: direct-csi-min-io-1r3j5
      {{- include "direct-pv.selectorLabels" . | nindent 8 }}
      annotations:
        created-by: kubectl-direct-csi
    spec:
      containers:
      - args:
        - --v=3
        - --timeout=300s
        - --csi-address=$(CSI_ENDPOINT)
        - --leader-election
        - --feature-gates=Topology=true
        - --strict-topology
        env:
        - name: CSI_ENDPOINT
          value: unix:///csi/csi.sock
        - name: KUBERNETES_CLUSTER_DOMAIN
          value: {{ .Values.kubernetesClusterDomain }}
        image: {{ .Values.csiMinIo.csiProvisioner.image.repository }}:{{ .Values.csiMinIo.csiProvisioner.image.tag
          | default .Chart.AppVersion }}
        name: csi-provisioner
        resources: {}
        securityContext:
          privileged: true
        terminationMessagePath: /var/log/controller-provisioner-termination-log
        terminationMessagePolicy: FallbackToLogsOnError
        volumeMounts:
        - mountPath: /csi
          mountPropagation: None
          name: socket-dir
      - args:
        - -v=3
        - --identity=direct-csi-min-io
        - --endpoint=$(CSI_ENDPOINT)
        - --readiness-port=30443
        - --controller
        env:
        - name: KUBE_NODE_NAME
          valueFrom:
            fieldRef:
              apiVersion: v1
              fieldPath: spec.nodeName
        - name: CSI_ENDPOINT
          value: unix:///csi/csi.sock
        - name: KUBERNETES_CLUSTER_DOMAIN
          value: {{ .Values.kubernetesClusterDomain }}
        image: {{ .Values.csiMinIo.directCsi.image.repository }}:{{ .Values.csiMinIo.directCsi.image.tag
          | default .Chart.AppVersion }}
        name: direct-csi
        ports:
        - containerPort: 20443
          name: validatinghook
          protocol: TCP
        - containerPort: 30443
          name: readinessport
          protocol: TCP
        - containerPort: 9898
          name: healthz
          protocol: TCP
        readinessProbe:
          httpGet:
            path: /ready
            port: readinessport
            scheme: HTTP
        resources: {}
        securityContext:
          privileged: true
        volumeMounts:
        - mountPath: /csi
          mountPropagation: None
          name: socket-dir
      serviceAccountName: {{ include "direct-pv.fullname" . }}-csi-min-io
      volumes:
      - hostPath:
          path: /var/lib/kubelet/plugins/direct-csi-min-io-controller
          type: DirectoryOrCreate
        name: socket-dir
