---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: nextcloud-data-pv
  namespace: default
  # annotations:
  #   pv.beta.kubernetes.io/gid: "1"
spec:
  capacity:
    storage: 500Gi
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Delete # Retain
  storageClassName: ceph-filesystem
  claimRef:
    name: nextcloud-data-pvc
    namespace: default
  csi:
    driver: rbd.csi.k8s.io
    readOnly: false
    volumeHandle: nextcloud-data

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: nextcloud-data-pvc
  namespace: default
spec:
  storageClassName: ceph-filesystem
  accessModes:
    - ReadWriteMany
  volumeMode: Filesystem
  resources:
    requests:
      storage: 500Gi
