---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: external-secrets
  namespace: flux-system
spec:
  interval: 15m
  releaseName: external-secrets
  targetNamespace: external-secrets
  chart:
    spec:
      chart: external-secrets
      version: 0.7.2
      sourceRef:
        kind: HelmRepository
        name: external-secrets
        namespace: flux-system
  maxHistory: 3
  install:
    createNamespace: true
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
  uninstall:
    keepHistory: false
  values:
    installCRDs: false
    serviceMonitor:
      enabled: true
    webhook:
      serviceMonitor:
        enabled: true
    certController:
      serviceMonitor:
        enabled: true
