---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: nfs-test
  namespace: openebs
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: "mayastor-3"
  volumeName: nfs-test
  resources:
    requests:
      storage: 100Gi
