---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: nfs-fileshare-linux
  namespace: openebs
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 250Gi
  storageClassName: openebs-kernel-nfs
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: nfs-photos
  namespace: openebs
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 250Gi
  storageClassName: openebs-kernel-nfs
