---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: direct-pv
  namespace: kube-system
spec:
  interval: 15m
  chart:
    spec:
      chart: ./kubernetes/src/direct-pv
      sourceRef:
        kind: GitRepository
        name: home-kubernetes
        namespace: flux-system
  maxHistory: 3
  install:
    crds: CreateReplace
    createNamespace: true
    remediation:
      retries: 3
  upgrade:
    crds: CreateReplace
    cleanupOnFail: true
    remediation:
      retries: 3
  uninstall:
    keepHistory: false
