---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: gpu-operator
  namespace: gpu-operator
spec:
  interval: 5m0s
  prune: false
  sourceRef:
    kind: GitRepository
    name: gpu-operator
  targetNamespace: gpu-operator
