---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  # https://github.com/solidDoWant/infra-mk2/blob/main/cluster/apps/kube-system/nvidia-gpu-operator/helm-release.yaml
  name: nvidia-gpu-operator
  namespace: nvidia

spec:
  interval: 5m
  chart:
    spec:
      # renovate: registryUrl=https://helm.ngc.nvidia.com/nvidia
      chart: gpu-operator
      version: v22.9.1
      sourceRef:
        kind: HelmRepository
        name: nvidia-charts
        namespace: flux-system
      interval: 5m
  values:
    nfd:
      enabled: false
    driver:
      enabled: false
    toolkit:
      env:
        - name: CONTAINERD_SOCKET
          value: '/var/run/k3s/containerd/containerd.sock'
