---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: vault
  namespace: hosted
spec:
  chart:
    spec:
      chart: vault
      reconcileStrategy: ChartVersion
      sourceRef:
        kind: HelmRepository
        name: hashicorp
        namespace: flux-system
  interval: 15m
  values:
    global:
      tlsDisable: true
    injector:
      loglevel: debug
      webhook:
        failurePolicy: Ignore
        namespaceSelector:
          matchExpressions:
            - key: kubernetes.io/metadata.name
              operator: NotIn
              values: ["hosted", "kube-system", "kube-public", "kube-node-lease"]
    server:
      dataStorage:
        storageClass: ceph-block
        mountPath: /tmp/vault/data
      # volumePermissions:
        # enabled: true
      extraVolumes:
        - type: configMap
          name: cells-vault
      postStart:
        - "/bin/sh"
        - "-c"
        - "sleep 5 && cp /vault/userconfig/cells-vault/bootstrap.sh /tmp/bootstrap.sh && chmod +x /tmp/bootstrap.sh && /tmp/bootstrap.sh"
